const SAVE_KEY = "coolCatCasinoSave";
const defaults = {money:100,reputation:50,machines:1,introSeen:false,day:1,minutes:480,playerX:830,playerY:760,quest:0,brokenFixed:false,repairStage:"not_started",parts:{wires:0,springs:0,screws:0,circuitBoards:0},foundParts:[],lastServiced:"None yet",expansions:[],music:20,sfx:65,weather:"Drizzle",weatherDaysLeft:3,seasonDay:1,restroomCleanliness:100,teasServed:0,spins:0,jackpots:0,vinnyMet:false,ghostMet:false,achievements:[],lastDaily:0,loyaltyPoints:0,mailClaimedDay:0,lostFoundDay:0,emergencyDay:0,cashOuts:0,machineCondition:100,serviceNeeded:false,visitorHappiness:82,totalVisitors:0};
let state = loadState();
let audioContext = null;
let musicTimer = null;
let toastTimer;
const keys = new Set();
const player = document.getElementById("player");
const world = document.getElementById("world");
const viewport = document.getElementById("game-viewport");
const prompt = document.getElementById("interaction-prompt");
const WORLD = {width:1800,height:1260};
const playerPosition = {x:state.playerX,y:state.playerY};
let joystickVector = {x:0,y:0};
let lastFrame = performance.now();
let nearbyTarget = null;
let vinnyVisible = false;

function loadState(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY))||{};const loaded={...defaults,...saved,parts:{...defaults.parts,...(saved.parts||{})}};if(loaded.brokenFixed)loaded.repairStage="complete";else if(loaded.quest>0&&loaded.repairStage==="not_started")loaded.repairStage="gathering";return loaded;}catch{return {...defaults,parts:{...defaults.parts}};}}
function saveState(){state.playerX=Math.round(playerPosition.x);state.playerY=Math.round(playerPosition.y);localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function updateHUD(){document.getElementById("money").textContent=Math.floor(state.money);document.getElementById("reputation").textContent=Math.round(state.reputation);document.getElementById("machines").textContent=state.machines;Object.keys(state.parts).forEach(part=>{const el=document.getElementById(`part-${part}`);if(el)el.textContent=state.parts[part];});document.getElementById("journal-alert").style.display=state.repairStage==="complete"&&!state.serviceNeeded?"none":"grid";const clean=Math.max(0,Math.round(state.restroomCleanliness));document.getElementById("cleanliness-fill").style.width=`${clean}%`;document.getElementById("restroom-status").textContent=clean>70?"SPARKLING":clean>35?"NEEDS A SWEEP":"OH DEAR";document.getElementById("restroom-status").style.color=clean>70?"#c7f3dc":clean>35?"#ffe17c":"#ff9b9b";document.getElementById("happiness-score").textContent=Math.round(state.visitorHappiness);updateAchievements();saveState();}
function toast(text){const el=document.getElementById("toast");el.textContent=text;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2300);}

function beginStory(){state.introSeen=true;document.getElementById("intro").classList.add("done");updateHUD();setTimeout(()=>speak("Benny","Onyx! Over here. Old Faithful is making that noise again."),900);}
document.getElementById("open-letter").onclick=()=>{document.getElementById("intro-card").classList.add("hidden");document.getElementById("letter").classList.remove("hidden");};
document.getElementById("begin-game").onclick=beginStory;
if(state.introSeen)document.getElementById("intro").classList.add("done");

function ensureAudio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();if(!musicTimer)startMusic();}
function tone(freq,duration=.12,type="sine",volume=.08){if(!audioContext||!state.sfx)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(volume*state.sfx/100,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);}
function startMusic(){const melody=[220,261.6,329.6,392,329.6,293.7,261.6,196];let i=0;musicTimer=setInterval(()=>{if(!audioContext||!state.music)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type="triangle";o.frequency.value=melody[i++%melody.length];g.gain.setValueAtTime(.018*state.music/100,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.9);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+1);},800);}
document.getElementById("sound-toggle").onclick=()=>{ensureAudio();state.music=state.music?0:20;document.getElementById("sound-toggle").textContent=state.music?"🔊":"🔇";saveState();};
document.addEventListener("pointerdown",ensureAudio,{once:true});

const npcData=[
 {name:"Benny",emoji:"🐈‍⬛",hat:"🧢",x:850,y:895,home:{x:850,y:895},lines:["Uncle Whiskers always said machines are just puzzles with bad attitudes.","Hit it with a wrench first. That's science.","Nothing's exploded today. Weird."]},
 {name:"Misty",emoji:"🐱",hat:"🎀",x:1450,y:430,home:{x:1450,y:430},lines:["The chips aren't the only thing stacked around here.","I don't gossip. I curate information.","Did anybody else see that?","My cousin says we need karaoke."]},
 {name:"Marmalade",emoji:"🐈",hat:"🍊",x:300,y:395,lines:["Every machine is lucky. Some are just shy.","I can feel a jackpot in my left whisker!", "Old Faithful and I have an understanding."]},
 {name:"Bianca",emoji:"🐱",hat:"💎",x:370,y:845,lines:["The décor is... historically committed.","Oh darling, that's just Uncle Whiskers checking on us.","This place needs a pool.","When are we getting a hotel?"]},
 {name:"Poppy",emoji:"🐈",hat:"🎓",x:1330,y:555,hats:["🎓","👒","🎩","⛑️","👑","🧢"],lines:["New machine smell? No, that's burned wires.","Tea first, roulette second!","I'd love an arcade.","Do you think this hat says 'responsible gambler'?"]},
 {name:"Sir Midnight",emoji:"🐈‍⬛",hat:"🕶️",x:510,y:910,lines:["I preferred it broken. It gave the room character.","...Nice place.","Hm.","Cool."]}
];
const npcs=[];
function createNPCs(){const layer=document.getElementById("npc-layer");npcData.forEach(data=>{const el=document.createElement("div");el.className="character npc";el.dataset.name=data.name;el.innerHTML=`<div class="speech-bubble"></div><div class="shadow"></div><div class="emoji-sprite">${data.emoji}<i>${data.hat}</i></div><span class="need-icon"></span><b class="name-tag">${data.name}</b>`;el.style.left=`${data.x}px`;el.style.top=`${data.y}px`;layer.appendChild(el);const staff=data.name==="Benny"||data.name==="Misty";const npc={...data,el,staff,active:true,activity:staff?"working":"arriving",targetX:data.x,targetY:data.y,nextMove:performance.now()+1500+Math.random()*2500,lifecycleAt:performance.now()+2500+Math.random()*2500,needs:{fun:65+Math.random()*25,thirst:70,restroom:15,money:30+Math.floor(Math.random()*50),happiness:80,patience:80}};npcs.push(npc);});}
createNPCs();

const walkPoints=[{x:260,y:350},{x:500,y:400},{x:820,y:400},{x:1050,y:500},{x:1420,y:340},{x:1400,y:560},{x:350,y:875},{x:850,y:920},{x:1220,y:915},{x:1450,y:900},{x:780,y:680},{x:1140,y:650}];
const activitySpots={entry:{x:840,y:1110},catm:{x:1185,y:790},slots:{x:330,y:535},tables:{x:850,y:690},tea:{x:1450,y:770},restroom:{x:1190,y:850},cashier:{x:1450,y:455},lounge:{x:420,y:730}};
function scheduleVisitor(npc,now){const n=npc.needs,hour=Math.floor(state.minutes/60);if(npc.activity==="leaving"){npc.active=false;npc.el.classList.add("leaving");setTimeout(()=>{npc.el.style.display="none";npc.lifecycleAt=performance.now()+(hour>=22?36000:18000)+Math.random()*24000;},700);return;}let activity;if(npc.activity==="arriving")activity="catm";else if(n.restroom>72)activity="restroom";else if(n.thirst<35)activity="tea";else if(n.money<8)activity="cashier";else if(n.fun<30)activity=Math.random()<.65?"slots":"tables";else if(n.patience<25||n.money<3||hour>=23)activity="leaving";else if(hour<12)activity=Math.random()<.6?"tea":"lounge";else if(hour<17)activity=Math.random()<.65?"slots":"tables";else if(hour<22)activity=Math.random()<.5?"tables":"lounge";else activity=Math.random()<.5?"cashier":"leaving";npc.activity=activity;const spot=activitySpots[activity]||activitySpots.entry;npc.targetX=spot.x+(Math.random()-.5)*55;npc.targetY=spot.y+(Math.random()-.5)*35;npc.lifecycleAt=now+6500+Math.random()*7000;npc.el.querySelector(".need-icon").textContent=activity==="tea"?"🍵":activity==="restroom"?"🚻":activity==="catm"?"🪙":activity==="leaving"?"🏠":"";if(npc.name==="Poppy"&&Math.random()<.45)npc.el.querySelector("i").textContent=npc.hats[Math.floor(Math.random()*npc.hats.length)];}
function resolveVisitorActivity(npc){const n=npc.needs;if(npc.activity==="catm"){n.money+=25;n.patience-=4;}if(npc.activity==="slots"||npc.activity==="tables"){const win=Math.random()<.4;n.fun+=win?30:12;n.money+=win?10:-5;n.happiness+=win?8:-2;}if(npc.activity==="tea"){n.thirst=100;n.happiness+=5;state.teasServed++;state.money+=2;}if(npc.activity==="restroom"){n.restroom=0;n.happiness+=state.restroomCleanliness>40?4:-10;state.restroomCleanliness=Math.max(0,state.restroomCleanliness-4);}if(npc.activity==="cashier"){n.money+=12;n.patience-=3;}if(npc.activity==="lounge"){n.patience+=20;n.happiness+=3;}n.fun=Math.max(0,n.fun-5);n.thirst=Math.max(0,n.thirst-7);n.restroom=Math.min(100,n.restroom+9);n.patience=Math.max(0,n.patience-5);n.happiness=Math.max(0,Math.min(100,n.happiness));if(Math.random()<.18)speak(npc.name,npc.lines[Math.floor(Math.random()*npc.lines.length)]);}
function updateNPC(npc,now,dt){if(npc.staff){npc.targetX=npc.home.x;npc.targetY=npc.home.y;}else{if(!npc.active){if(now<npc.lifecycleAt)return;npc.active=true;npc.el.style.display="block";npc.el.classList.remove("leaving");npc.el.classList.add("arriving");npc.x=activitySpots.entry.x;npc.y=activitySpots.entry.y;npc.activity="arriving";npc.needs={fun:55,thirst:70,restroom:10,money:25+Math.floor(Math.random()*40),happiness:78,patience:75};state.totalVisitors++;scheduleVisitor(npc,now);setTimeout(()=>npc.el.classList.remove("arriving"),1000);}else if(now>npc.lifecycleAt&&Math.hypot(npc.x-npc.targetX,npc.y-npc.targetY)<18){resolveVisitorActivity(npc);scheduleVisitor(npc,now);}}
 const dx=npc.targetX-npc.x,dy=npc.targetY-npc.y,d=Math.hypot(dx,dy);if(d>5){const speed=38*dt;npc.x+=dx/d*speed;npc.y+=dy/d*speed;npc.el.classList.add("walking");npc.el.style.left=`${npc.x}px`;npc.el.style.top=`${npc.y}px`;}else npc.el.classList.remove("walking");}

function speak(name,text){const npc=npcs.find(n=>n.name===name);if(!npc)return;const bubble=npc.el.querySelector(".speech-bubble");bubble.textContent=text;bubble.classList.add("show");setTimeout(()=>bubble.classList.remove("show"),3300);}
function talkToNPC(npc){tone(440,.09);if(npc.name==="Benny")return state.serviceNeeded?openRoutineService():openBennyWorkshop();if(npc.name==="Misty")return openMistyServices();const line=npc.lines[Math.floor(Math.random()*npc.lines.length)];speak(npc.name,line);}

const solidRects=[
 {x:60,y:110,w:1680,h:72},{x:60,y:1145,w:690,h:45},{x:1020,y:1145,w:720,h:45},{x:60,y:110,w:40,h:1080},{x:1700,y:110,w:40,h:1080},
 {x:150,y:280,w:510,h:205},{x:780,y:280,w:285,h:165},{x:965,y:475,w:260,h:155},
 {x:1325,y:275,w:330,h:120},{x:1325,y:530,w:330,h:115},
 {x:305,y:900,w:315,h:150},{x:740,y:920,w:295,h:170},{x:980,y:870,w:280,h:220},{x:1310,y:870,w:280,h:220}
];
function collides(x,y){const r=22;return solidRects.some(rect=>x+r>rect.x&&x-r<rect.x+rect.w&&y+r>rect.y&&y-r<rect.y+rect.h);}
if(collides(playerPosition.x,playerPosition.y)){playerPosition.x=830;playerPosition.y=760;}
function movePlayer(dx,dy,dt){if(!dx&&!dy){player.classList.remove("walking");return;}const mag=Math.hypot(dx,dy)||1,step=180*dt;dx=dx/mag*step;dy=dy/mag*step;const nx=Math.max(90,Math.min(WORLD.width-90,playerPosition.x+dx));const ny=Math.max(160,Math.min(WORLD.height-70,playerPosition.y+dy));if(!collides(nx,playerPosition.y))playerPosition.x=nx;if(!collides(playerPosition.x,ny))playerPosition.y=ny;player.classList.add("walking");player.style.left=`${playerPosition.x}px`;player.style.top=`${playerPosition.y}px`;}
function updateCamera(){const vw=viewport.clientWidth,vh=viewport.clientHeight;const x=Math.min(0,Math.max(vw-WORLD.width,vw/2-playerPosition.x));const y=Math.min(0,Math.max(vh-WORLD.height,vh/2-playerPosition.y));world.style.transform=`translate3d(${Math.round(x)}px,${Math.round(y)}px,0)`;}

const requiredParts={wires:1,springs:1,screws:2,circuitBoards:1};
const partInfo={wires:{icon:"〰️",name:"Wires"},springs:{icon:"➰",name:"Springs"},screws:{icon:"🔩",name:"Screws"},circuitBoards:{icon:"🟩",name:"Circuit Board"}};
const pickupDefs=[
 {id:"wire-floor",part:"wires",x:690,y:700},{id:"spring-floor",part:"springs",x:1260,y:790},{id:"screw-floor-a",part:"screws",x:670,y:1080},{id:"screw-floor-b",part:"screws",x:1650,y:800},{id:"board-floor",part:"circuitBoards",x:1100,y:760},
 {id:"parts-box-a",box:true,x:160,y:690},{id:"parts-box-b",box:true,x:1280,y:1080}
];
const actionTargets=[{x:215,y:505,action:"slots",label:"Play Old Faithful"},{x:350,y:505,action:"slots",label:"Play Meow Mix"},{x:490,y:505,action:"repair",label:"Inspect broken machine"},{x:590,y:505,action:"buyMachine",label:"Buy a slot machine"},{x:920,y:465,action:"blackjack",label:"Play Blackjack"},{x:1090,y:650,action:"roulette",label:"Play Roulette"},{x:1480,y:665,action:"tea",label:"Order Catnip Tea"},{x:1185,y:790,action:"catm",label:"Use CATM"},{x:1580,y:790,action:"catm",label:"Use CATM"},{x:1190,y:850,action:"restroom",label:"Clean Powder Paw Room"}];
function createPickups(){const layer=document.getElementById("pickup-layer");pickupDefs.forEach(item=>{const el=document.createElement("div");el.className=`pickup ${item.box?"parts-box":""}`;el.dataset.pickup=item.id;el.style.left=`${item.x}px`;el.style.top=`${item.y}px`;el.innerHTML=item.box?`<i>📦</i><b>PARTS BOX</b>`:`<i>${partInfo[item.part].icon}</i><b>${partInfo[item.part].name.toUpperCase()}</b>`;layer.appendChild(el);item.el=el;actionTargets.push({x:item.x+20,y:item.y+20,pickup:item,label:item.box?"Search parts box":`Pick up ${partInfo[item.part].name}`});});refreshPickups();}
function refreshPickups(){pickupDefs.forEach(item=>{if(!item.el)return;const unavailable=state.repairStage==="not_started"||state.repairStage==="complete"||state.foundParts.includes(item.id);item.el.classList.toggle("collected",unavailable);});}
function collectPickup(item){if(state.repairStage==="not_started")return toast("Benny might know what these are for.");if(state.foundParts.includes(item.id))return;let part=item.part;if(item.box){const missing=Object.keys(requiredParts).filter(key=>state.parts[key]<requiredParts[key]);part=missing.length?missing[Math.floor(Math.random()*missing.length)]:Object.keys(requiredParts)[Math.floor(Math.random()*4)];}state.parts[part]++;state.foundParts.push(item.id);item.el.classList.add("collected");toast(`Found ${partInfo[part].name}!`);tone(620,.18);updateRepairObjective();updateHUD();}
createPickups();
function findNearby(){let best=null,distance=75;actionTargets.forEach(target=>{if(target.pickup&&(state.repairStage==="not_started"||state.repairStage==="complete"||state.foundParts.includes(target.pickup.id)))return;const d=Math.hypot(playerPosition.x-target.x,playerPosition.y-target.y);if(d<distance){best=target;distance=d;}});npcs.forEach(npc=>{const d=Math.hypot(playerPosition.x-npc.x,playerPosition.y-npc.y);if(d<distance){best={npc,label:`Talk to ${npc.name}`};distance=d;}});if(vinnyVisible){const vinny=document.getElementById("vinny"),x=parseFloat(vinny.style.left),y=parseFloat(vinny.style.top),d=Math.hypot(playerPosition.x-x,playerPosition.y-y);if(d<distance)best={action:"vinny",label:"Talk to Vinny"};}nearbyTarget=best;prompt.classList.toggle("hidden",!best);if(best)prompt.querySelector("span").textContent=best.label;}

function interact(){if(!nearbyTarget)return;if(nearbyTarget.npc)return talkToNPC(nearbyTarget.npc);if(nearbyTarget.pickup)return collectPickup(nearbyTarget.pickup);const actions={slots:openSlots,repair:inspectBrokenMachine,buyMachine:buyMachine,blackjack:()=>openMiniGame("Blackjack",10,22),roulette:()=>openMiniGame("Roulette",10,30),tea:buyTea,catm:openCATM,restroom:cleanRestroom,vinny:talkVinny};actions[nearbyTarget.action]?.();}
function showDialog(html){const dialog=document.getElementById("dialog");document.getElementById("dialog-body").innerHTML=html;if(!dialog.open)dialog.showModal();}
document.querySelector(".dialog-close").onclick=()=>document.getElementById("dialog").close();
document.querySelectorAll("[data-action]").forEach(element=>element.addEventListener("click",event=>{event.stopPropagation();const action=element.dataset.action;({slots:openSlots,repair:inspectBrokenMachine,buyMachine:buyMachine,catm:openCATM,blackjack:()=>openMiniGame("Blackjack",10,22),roulette:()=>openMiniGame("Roulette",10,30)}[action]||(()=>{}))();}));

function openSlots(){showDialog(`<div class="dialog-scene"><p class="chapter">Lucky Paw Slots</p><h2>Old Faithful</h2><div class="reels"><span id="r1">🐟</span><span id="r2">7</span><span id="r3">🐾</span></div><p id="game-result">Three matching symbols win 60 coins. Two win 15.</p><button id="spin-game">SPIN — 5 COINS</button></div>`);document.getElementById("spin-game").onclick=spinSlots;}
function spinSlots(){if(state.money<5)return document.getElementById("game-result").textContent="Not enough Catnip Coins.";ensureAudio();state.spins++;state.loyaltyPoints++;state.money-=5;const symbols=["🐟","7","🐾","🧶","🐱"],result=[];[1,2,3].forEach((n,i)=>{result.push(symbols[Math.floor(Math.random()*symbols.length)]);document.getElementById(`r${n}`).textContent=result[i];tone(250+i*80,.12,"square");});if(new Set(result).size===1){state.money+=60;state.reputation+=2;state.jackpots++;document.getElementById("game-result").textContent="JACKPOT! +60 coins!";jackpot();}else if(new Set(result).size===2){state.money+=15;document.getElementById("game-result").textContent="A tidy little win! +15 coins.";}else document.getElementById("game-result").textContent="Not this time. Old Faithful coughs politely.";updateHUD();}
function jackpot(){npcs.forEach(npc=>speak(npc.name,npc.name==="Sir Midnight"?"...Nice.":"JACKPOT!"));for(let i=0;i<24;i++){const p=document.createElement("i");p.className="particle";p.style.left=`${playerPosition.x+(Math.random()-.5)*300}px`;p.style.top=`${playerPosition.y+(Math.random()-.5)*140}px`;document.getElementById("world-effects").appendChild(p);setTimeout(()=>p.remove(),1300);}tone(880,.4,"triangle",.15);}
function hasAllParts(){return Object.keys(requiredParts).every(part=>state.parts[part]>=requiredParts[part]);}
function updateRepairObjective(){if(state.serviceNeeded)return document.getElementById("quest-text").textContent="Ask Benny to service the sparking machine";if(state.repairStage==="not_started")document.getElementById("quest-text").textContent="Talk to Benny about the broken machine";else if(state.repairStage==="gathering"){const missing=Object.keys(requiredParts).filter(part=>state.parts[part]<requiredParts[part]);document.getElementById("quest-text").textContent=missing.length?`Gather repair parts (${Object.keys(requiredParts).length-missing.length}/${Object.keys(requiredParts).length} types ready)`:"Return to Benny with the repair parts";}else if(state.repairStage==="repairing")document.getElementById("quest-text").textContent="Help Benny repair the machine";else document.getElementById("quest-text").textContent="Earn 200 Catnip Coins for the first expansion";}
function beginRepairQuest(){state.repairStage="gathering";state.quest=1;document.getElementById("dialog").close();refreshPickups();updateRepairObjective();updateHUD();toast("Repair quest started — parts are scattered around the casino.");setTimeout(()=>speak("Poppy","New machine smell? No, that's burned wires."),900);}
function openBennyWorkshop(){if(state.repairStage==="complete")return showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Workshop</h2><p>“Nothing's exploded. Weird.”</p><div class="story-note">Last serviced: ${state.lastServiced}</div></div>`);if(state.repairStage==="not_started"){showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny</h2><p>“Uncle Whiskers always said machines are just puzzles with bad attitudes.”</p><p>Old Lucky Number Three needs wires, a spring, two screws, and a circuit board. Some parts are lying around; check the old boxes too.</p><button id="accept-repair">HELP BENNY REPAIR IT</button></div>`);document.getElementById("accept-repair").onclick=beginRepairQuest;return;}const ready=hasAllParts();showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Workshop</h2><p>“${ready?"Hit it with a wrench first. That's science.":"Nothing's exploded today. Weird."}”</p>${partsChecklist()}<p>Short on something? Benny keeps questionably organized spares.</p><div class="benny-shop">${Object.keys(requiredParts).map(part=>`<button data-buy-part="${part}">Buy ${partInfo[part].name} — ${part==="circuitBoards"?8:4}🪙</button>`).join("")}</div>${ready?'<button id="start-repair">REPAIR THE MACHINE</button>':''}</div>`);document.querySelectorAll("[data-buy-part]").forEach(button=>button.onclick=()=>buyPart(button.dataset.buyPart));if(ready)document.getElementById("start-repair").onclick=startRepairAnimation;}
function buyPart(part){const cost=part==="circuitBoards"?8:4;if(state.money<cost)return toast("Not enough Catnip Coins.");state.money-=cost;state.parts[part]++;updateRepairObjective();updateHUD();state.serviceNeeded?openRoutineService():openBennyWorkshop();}
function partsChecklist(){return `<div class="journal-parts">${Object.keys(requiredParts).map(part=>{const have=state.parts[part],need=requiredParts[part];return `<div class="journal-part ${have>=need?'have':''}">${partInfo[part].icon} ${partInfo[part].name}<br><b>${have}/${need}</b></div>`;}).join("")}</div>`;}
function inspectBrokenMachine(){if(state.repairStage==="not_started")return toast("OUT OF ORDER — Benny will know what it needs.");if(state.repairStage==="complete")return openSlots();showMaintenanceJournal();}
function startRepairAnimation(){if(!hasAllParts())return toast("The repair kit is still missing parts.");ensureAudio();state.repairStage="repairing";updateRepairObjective();showDialog(`<div class="dialog-scene"><p class="chapter">Maintenance Team-Up</p><h2>Onyx & Benny at Work</h2><div class="repair-stage"><div class="repair-cats">🐈‍⬛　🐈‍⬛</div><div class="repair-wrench">🔧</div><div class="repair-sparks">✦ ⚡ ✦</div><div class="progress-track"><div class="progress-fill" id="repair-progress"></div></div></div><p id="repair-status">Benny is considering which wrench looks smartest...</p></div>`);document.querySelector(".dialog-close").disabled=true;let progress=0;const messages=["Removing a suspicious amount of lint...","Onyx holds the flashlight perfectly...","Benny applies calibrated percussive maintenance...","Reconnecting the last wire..."];const timer=setInterval(()=>{progress+=10;document.getElementById("repair-progress").style.width=`${progress}%`;document.getElementById("repair-status").textContent=messages[Math.min(messages.length-1,Math.floor(progress/30))];tone(progress%20?430:180,.08,progress%20?"square":"sawtooth");spawnRepairSparks();if(progress>=100){clearInterval(timer);setTimeout(finishRepair,350);}},280);}
function spawnRepairSparks(){for(let i=0;i<3;i++){const spark=document.createElement("i");spark.className="particle";spark.style.left=`${470+Math.random()*80}px`;spark.style.top=`${390+Math.random()*60}px`;document.getElementById("world-effects").appendChild(spark);setTimeout(()=>spark.remove(),1200);}}
function finishRepair(){Object.keys(requiredParts).forEach(part=>state.parts[part]-=requiredParts[part]);state.brokenFixed=true;state.repairStage="complete";state.quest=2;state.machines++;state.reputation+=8;state.lastServiced=`Lucky Number Three — Day ${state.day}`;const machine=document.querySelector(".machine.broken");if(machine){machine.classList.remove("broken");machine.querySelector(".breakdown-sign")?.remove();machine.querySelector("b").textContent="BENNY'S BEST";}document.querySelector(".dialog-close").disabled=false;showDialog(`<div class="dialog-scene"><div class="portrait">🎰✨</div><h2>Back in Business!</h2><p>Lucky Number Three hums to life and begins earning Catnip Coins.</p><div class="story-note">Benny: “Only two screws left over. That's basically a record.”</div></div>`);refreshPickups();updateRepairObjective();updateHUD();tone(880,.45,"triangle",.16);speak("Poppy","New machine smell? No, that's burned wires.");setTimeout(()=>speak("Sir Midnight","I preferred it broken. It gave the room character."),1800);}
function showMaintenanceJournal(){const status=state.repairStage==="complete"?"Operational":state.repairStage==="repairing"?"Repair in progress":"Out of Order";showDialog(`<div class="journal-list"><p class="chapter">Maintenance Journal</p><h2>🔧 Uncle Whiskers' Service Log</h2><div class="journal-row ${state.brokenFixed?'done':''}"><div><b>Lucky Number Three</b><small> Slot Machine • West Floor</small></div><strong>${status}</strong></div>${partsChecklist()}<div class="journal-row"><span>Repair progress</span><b>${state.repairStage==="complete"?'100%':hasAllParts()?'Parts ready':state.repairStage==="not_started"?'Not diagnosed':'Gathering parts'}</b></div><div class="story-note">Last machine serviced: ${state.lastServiced}</div></div>`);}
document.getElementById("journal-button").onclick=showMaintenanceJournal;
function openMiniGame(name,cost,prize){showDialog(`<div class="dialog-scene"><div class="portrait">${name==="Blackjack"?"🃏":"🎡"}</div><h2>${name}</h2><p id="game-result">A round costs ${cost} coins. Win ${prize}.</p><button id="play-mini">PLAY</button></div>`);document.getElementById("play-mini").onclick=()=>{if(state.money<cost)return document.getElementById("game-result").textContent="Not enough coins.";state.money-=cost;const win=Math.random()<.43;if(win){state.money+=prize;document.getElementById("game-result").textContent=`A classy win! +${prize} coins.`;tone(660,.2);}else document.getElementById("game-result").textContent="The house wins. It tries not to look smug.";updateHUD();};}
function buyTea(){if(state.money<3)return toast("Even tea requires three coins.");state.money-=3;state.teasServed++;state.visitorHappiness=Math.min(100,state.visitorHappiness+1);toast("Minty Meow Tea: movement feels extra smooth. 🍵");tone(520,.18);updateHUD();}
function machineCost(){return 50+Math.max(0,state.machines-1)*25;}
function buyMachine(){const cost=machineCost();if(state.money<cost)return toast(`A new machine costs ${cost} Catnip Coins.`);state.money-=cost;state.machines++;state.machineCondition=Math.min(100,state.machineCondition+10);state.reputation+=1;toast(`New slot machine installed! Income increased. Next: ${machineCost()} coins.`);tone(620,.18);updateHUD();}
document.getElementById("buy-machine-button").onclick=buyMachine;
function openCATM(){showDialog(`<div class="dialog-scene"><div class="portrait">🏧🐾</div><h2>CATM</h2><p>Catnip Automated Teller Machine</p><div class="service-grid"><button id="catm-withdraw">Withdraw 20 coins</button><button id="catm-emergency">Emergency coin recovery</button></div><p class="visitor-detail">Visitors use CATMs before playing so they don't wander forever with empty pockets.</p></div>`);document.getElementById("catm-withdraw").onclick=()=>{state.money+=20;state.loyaltyPoints++;toast("Withdrew 20 Catnip Coins.");updateHUD();};document.getElementById("catm-emergency").onclick=()=>{if(state.money>0)return toast("Emergency coins are only for totally empty pockets.");if(state.emergencyDay===state.day)return toast("Emergency recovery already used today.");state.money=15;state.emergencyDay=state.day;toast("CATM issued 15 emergency coins. Uncle would approve.");updateHUD();};}
function openMistyServices(){showDialog(`<div class="dialog-scene"><div class="portrait">🐱🎀</div><h2>Misty's Counter</h2><p>“I don't gossip. I curate information.”</p><div class="service-grid"><button id="daily-reward">Daily reward</button><button id="loyalty-reward">Loyalty reward</button><button id="lost-found">Lost & found</button><button id="mail-button">Mail</button><button id="emergency-misty">Emergency coins</button><button id="cash-bonus">Cash out bonus</button></div></div>`);document.getElementById("daily-reward").onclick=()=>{if(state.lastDaily===state.day)return toast("Misty says you already got today's reward.");state.money+=25;state.lastDaily=state.day;toast("Daily reward: +25 coins.");updateHUD();};document.getElementById("loyalty-reward").onclick=()=>{if(state.loyaltyPoints<3)return toast("Earn 3 loyalty points from CATMs and games first.");state.loyaltyPoints-=3;state.money+=35;toast("Loyalty reward: +35 coins.");updateHUD();};document.getElementById("lost-found").onclick=()=>{if(state.lostFoundDay===state.day)return toast("Lost and found is empty today.");state.lostFoundDay=state.day;state.parts.screws++;toast("Found a screw in a velvet coin pouch.");updateHUD();};document.getElementById("mail-button").onclick=()=>{if(state.mailClaimedDay===state.day)return toast("No more mail today.");state.mailClaimedDay=state.day;state.reputation+=1;toast("Fan mail from a kitten: +1 reputation.");updateHUD();};document.getElementById("emergency-misty").onclick=()=>{if(state.money>0)return toast("Misty only opens the emergency tin when you're broke.");state.money=20;toast("Misty slides over 20 coins and pretends not to care.");updateHUD();};document.getElementById("cash-bonus").onclick=()=>{if(state.money<100)return toast("Cash out bonus starts at 100 coins.");state.money+=10;state.cashOuts++;toast("Responsible cash-out bonus: +10 coins.");updateHUD();};}
function cleanRestroom(){state.restroomCleanliness=100;state.reputation+=1;toast("The Powder Paw Room sparkles. Customers appreciate it.");tone(540,.2);updateHUD();}
function openRoutineService(){const ready=state.parts.wires>=1&&state.parts.screws>=1;showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Service Call</h2><p>“Hit it with a wrench first. That's science.”</p><p>Routine repair needs 1 wire and 1 screw.</p><div class="journal-parts"><div class="journal-part ${state.parts.wires>=1?'have':''}">〰️ Wires<br><b>${state.parts.wires}/1</b></div><div class="journal-part ${state.parts.screws>=1?'have':''}">🔩 Screws<br><b>${state.parts.screws}/1</b></div></div><div class="benny-shop"><button data-buy-part="wires">Buy Wires — 4🪙</button><button data-buy-part="screws">Buy Screws — 4🪙</button></div>${ready?'<button id="routine-service">SERVICE MACHINE</button>':''}</div>`);document.querySelectorAll("[data-buy-part]").forEach(button=>button.onclick=()=>buyPart(button.dataset.buyPart));if(ready)document.getElementById("routine-service").onclick=()=>{state.parts.wires--;state.parts.screws--;state.serviceNeeded=false;state.machineCondition=100;state.lastServiced=`Routine service — Day ${state.day}`;document.querySelector(".machine.broken")?.classList.remove("broken");toast("Benny services the machine. It stops making goblin noises.");tone(700,.25);updateRepairObjective();updateHUD();document.getElementById("dialog").close();};}

const achievementDefs=[
 ["First Spin","Take your first spin",()=>state.spins>=1],["First Jackpot","Hit any jackpot",()=>state.jackpots>=1],["Repair First Machine","Bring Lucky Number Three back",()=>state.brokenFixed],["Meet Vinny","Talk to Vinny",()=>state.vinnyMet],["Meet Uncle Whiskers' Ghost","See Uncle Whiskers after 10 PM",()=>state.ghostMet],["Own 10 Machines","Build a respectable slot row",()=>state.machines>=10],["Own 25 Machines","Become a machine mogul",()=>state.machines>=25],["Reach 100 Reputation","Become the talk of the town",()=>state.reputation>=100],["Serve 100 Teas","Keep the casino cozy",()=>state.teasServed>=100],["Become Local Legend","Reach 150 reputation and full resort dreams",()=>state.reputation>=150]
];
function updateAchievements(){let changed=false;achievementDefs.forEach(([name,,test])=>{if(test()&&!state.achievements.includes(name)){state.achievements.push(name);changed=true;}});return changed;}
function showAchievements(){updateAchievements();showDialog(`<div class="dialog-scene"><p class="chapter">Separate from Blueprints</p><h2>Achievements</h2><div class="achievement-grid">${achievementDefs.map(([name,desc])=>`<div class="achievement-card ${state.achievements.includes(name)?'unlocked':''}">${state.achievements.includes(name)?'🏆':'🔒'} <b>${name}</b><br><small>${desc}</small></div>`).join("")}</div></div>`);}
document.getElementById("achievements-button").onclick=showAchievements;

const expansions=[{name:"Better Slot Machines",cost:250,rep:55,machines:10},{name:"Tea Bar",cost:350,rep:65,machines:12},{name:"Arcade",cost:550,rep:75,machines:14},{name:"Aquarium",cost:750,rep:85,machines:16},{name:"VIP Lounge",cost:950,rep:95,machines:18},{name:"Pool",cost:1200,rep:105,machines:20},{name:"Hotel Tower",cost:1500,rep:120,machines:22},{name:"Penthouse",cost:1900,rep:140,machines:25},{name:"Parking Garage",cost:2300,rep:155,machines:28},{name:"Full Resort",cost:3000,rep:175,machines:30}];
function renderExpansions(){document.getElementById("expansion-list").innerHTML=expansions.map((item,i)=>{const owned=state.expansions.includes(item.name),locked=state.reputation<item.rep||state.machines<item.machines;return `<article class="expansion-item ${owned?'unlocked':''}"><b>${owned?'✓ ':locked?'🔒 ':''}${i+1}. ${item.name}</b><small>${owned?'Built and bustling':locked?`Requires ${item.rep} reputation and ${item.machines} machines`:`Renovation milestone • ${item.cost} coins`}</small><button data-build="${i}" ${owned||locked?'disabled':''}>${owned?'BUILT':`BUILD — ${item.cost}`}</button></article>`;}).join("");document.querySelectorAll("[data-build]").forEach(button=>button.onclick=()=>buildExpansion(+button.dataset.build));}
function buildExpansion(index){const item=expansions[index];if(state.money<item.cost)return toast(`You need ${item.cost} coins.`);state.money-=item.cost;state.reputation+=8;state.expansions.push(item.name);toast(`${item.name} is now open!`);renderExpansions();updateHUD();}
document.getElementById("expansion-button").onclick=()=>{renderExpansions();document.getElementById("expansion-panel").classList.add("open");};document.querySelector(".panel-close").onclick=()=>document.getElementById("expansion-panel").classList.remove("open");

function showVinny(){const el=document.getElementById("vinny");el.classList.remove("hidden");el.style.left="1240px";el.style.top="770px";vinnyVisible=true;setTimeout(()=>{if(vinnyVisible){el.classList.add("hidden");vinnyVisible=false;}},22000);}
function talkVinny(){state.vinnyMet=true;const lines=["These coins? Completely legitimate. Mostly.","Never trust a dealer with cleaner paws than you.","I know a guy. I am the guy."];const line=lines[Math.floor(Math.random()*lines.length)];showDialog(`<div class="dialog-scene"><div class="portrait">🦝🎩</div><h2>Vinny</h2><p>“${line}”</p><p>Give Vinny 15 coins for a mystery deal?</p><button id="vinny-deal">MAKE THE DEAL</button></div>`);document.getElementById("vinny-deal").onclick=()=>{if(state.money<15)return toast("Vinny sighs. 'Come back with the lettuce.'");state.money-=15;if(state.repairStage==="gathering"&&Math.random()<.45){const missing=Object.keys(requiredParts).filter(part=>state.parts[part]<requiredParts[part]);const part=missing.length?missing[Math.floor(Math.random()*missing.length)]:"screws";state.parts[part]++;toast(`Vinny's envelope contained ${partInfo[part].name}. Don't ask.`);updateRepairObjective();}else{const reward=Math.random()<.7?30:5;state.money+=reward;toast(`Vinny's envelope contained ${reward} coins.`);}document.getElementById("vinny-deal").disabled=true;updateHUD();};}
setTimeout(showVinny,18000+Math.random()*18000);setInterval(()=>{if(!vinnyVisible&&Math.random()<.45)showVinny();},45000);

document.addEventListener("keydown",event=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","w","a","s","d","W","A","S","D"].includes(event.key))event.preventDefault();keys.add(event.key.toLowerCase());if(event.key.toLowerCase()==="e"||event.key==="Enter")interact();});document.addEventListener("keyup",event=>keys.delete(event.key.toLowerCase()));
const joystick=document.getElementById("joystick"),knob=document.getElementById("joystick-knob");function setJoystick(event){const rect=joystick.getBoundingClientRect(),cx=rect.left+rect.width/2,cy=rect.top+rect.height/2,dx=event.clientX-cx,dy=event.clientY-cy,d=Math.hypot(dx,dy),max=36,scale=d>max?max/d:1;dx*=scale;dy*=scale;joystickVector={x:dx/max,y:dy/max};knob.style.transform=`translate(${dx}px,${dy}px)`;}joystick.addEventListener("pointerdown",event=>{joystick.setPointerCapture(event.pointerId);setJoystick(event);});joystick.addEventListener("pointermove",event=>{if(joystick.hasPointerCapture(event.pointerId))setJoystick(event);});function releaseJoystick(){joystickVector={x:0,y:0};knob.style.transform="";}joystick.addEventListener("pointerup",releaseJoystick);joystick.addEventListener("pointercancel",releaseJoystick);prompt.addEventListener("pointerdown",interact);

const weatherTypes=["Sunny","Drizzle","Rain","Thunderstorm","Snow"],weatherIcons={Sunny:"☀️",Drizzle:"🌦️",Rain:"🌧️",Thunderstorm:"⛈️",Snow:"❄️"},seasons=["Spring","Summer","Autumn","Winter"],seasonIcons={Spring:"🌸",Summer:"☀️",Autumn:"🍂",Winter:"❄️"};
function currentSeason(){return seasons[Math.floor((state.day-1)/14)%seasons.length];}
function chooseWeather(){const season=currentSeason(),pool=season==="Winter"?["Snow","Snow","Sunny","Rain"]:season==="Summer"?["Sunny","Sunny","Drizzle","Thunderstorm"]:["Sunny","Drizzle","Rain","Thunderstorm"];state.weather=pool[Math.floor(Math.random()*pool.length)];state.weatherDaysLeft=2+Math.floor(Math.random()*4);applyWeather();}
function applyWeather(){document.getElementById("weather-label").textContent=`${weatherIcons[state.weather]} ${state.weather}`;document.getElementById("season-chip").textContent=`${seasonIcons[currentSeason()]} ${currentSeason()}`;let layer=document.querySelector(".weather-particles");if(!layer){layer=document.createElement("div");layer.className="weather-particles";document.querySelector(".outside-strip").appendChild(layer);}layer.innerHTML="";if(state.weather==="Snow")for(let i=0;i<35;i++){const flake=document.createElement("i");flake.className="snowflake";flake.textContent="❄";flake.style.left=`${Math.random()*100}%`;flake.style.top=`${-Math.random()*800}px`;flake.style.animationDelay=`${Math.random()*6}s`;layer.appendChild(flake);}if(state.weather==="Thunderstorm"){const flash=document.createElement("i");flash.className="thunder-flash";layer.appendChild(flash);}}
function newGameDay(){state.weatherDaysLeft--;if(state.weatherDaysLeft<=0)chooseWeather();state.restroomCleanliness=Math.max(0,state.restroomCleanliness-2);state.seasonDay=(state.seasonDay||1)+1;updateHUD();}
function weatherComment(){if(state.weather==="Rain"||state.weather==="Drizzle")return Math.random()<.5?["Bianca","Darling, rainy days are excellent for tea."]:["Marmalade","I refuse to get my paws wet."];if(state.weather==="Snow")return ["Poppy","Snow is just confetti with boundaries."];if(state.weather==="Thunderstorm")return ["Misty","That thunder was not one of Benny's machines. Probably."];return ["Bianca","Finally, weather worthy of my sunglasses."];}
setInterval(()=>{if(Math.random()<.28){const [name,line]=weatherComment();speak(name,line);}if(state.weather==="Thunderstorm"&&Math.random()<.35){const flash=document.querySelector(".thunder-flash");if(flash){flash.classList.remove("flash");void flash.offsetWidth;flash.classList.add("flash");tone(70,.5,"sawtooth",.05);}}},14000);

let ghostAccumulator=0,ghostPresent=false;
const ghostSpots=[{x:1090,y:555,type:"roulette"},{x:1450,y:690,type:"tea bar"},{x:345,y:930,type:"favorite chair"}];
function updateGhost(dt){const hour=Math.floor(state.minutes/60);if(hour<22&&hour>=6)return;ghostAccumulator+=dt;if(ghostAccumulator<18||ghostPresent)return;ghostAccumulator=0;if(Math.random()>.42)return;state.ghostMet=true;const ghost=document.getElementById("uncle-ghost"),spot=ghostSpots[Math.floor(Math.random()*ghostSpots.length)];ghost.style.left=`${spot.x}px`;ghost.style.top=`${spot.y}px`;ghost.classList.remove("hidden");ghostPresent=true;const messages=["You feel like Uncle Whiskers is proud of you.","Someone left fresh catnip tea on the table. Strange...","For a moment, you could swear you heard him laugh."];setTimeout(()=>toast(messages[Math.floor(Math.random()*messages.length)]),1200);if(Math.random()<.3){setTimeout(()=>speak("Misty","Did anybody else see that?"),1700);setTimeout(()=>speak("Bianca","Oh darling, that's just Uncle Whiskers checking on us."),3200);}setTimeout(()=>{if(spot.type==="roulette"&&Math.random()<.5){toast("The roulette ball lands on Uncle Whiskers' old number. The chair is suddenly empty.");tone(720,.35,"triangle");}ghost.classList.add("hidden");ghostPresent=false;},11000);}
function updateClock(dt){const beforeDay=state.day;state.minutes+=dt/12;if(state.minutes>=1440){state.minutes-=1440;state.day++;newGameDay();}const hours=Math.floor(state.minutes/60),mins=Math.floor(state.minutes%60),displayHour=hours%12||12,period=hours<12?"AM":"PM";document.getElementById("game-time").textContent=`${displayHour}:${String(mins).padStart(2,"0")} ${period}`;document.getElementById("day-label").textContent=`DAY ${state.day}`;const night=hours>=19||hours<6;document.getElementById("day-night").style.opacity=night?".46":hours>=17?".2":"0";if(beforeDay!==state.day)saveState();}
function updateWorldSystems(dt){const visitors=npcs.filter(n=>!n.staff&&n.active);document.getElementById("visitor-count").textContent=visitors.length;const avg=visitors.length?visitors.reduce((sum,n)=>sum+n.needs.happiness,0)/visitors.length:82;state.visitorHappiness=Math.max(0,Math.min(100,(state.visitorHappiness*.98)+(avg*.02)));if(state.restroomCleanliness<35)state.visitorHappiness=Math.max(0,state.visitorHappiness-dt*.4);if(state.brokenFixed&&!state.serviceNeeded){state.machineCondition-=dt*(0.012+state.machines*.001);if(state.machineCondition<=0){state.serviceNeeded=true;state.machineCondition=0;state.reputation=Math.max(0,state.reputation-3);toast("A slot machine starts coughing sparks. Benny is already frowning.");speak("Benny","Machines are just puzzles with bad attitudes.");document.querySelector('.machine:not(.locked)')?.classList.add("broken");updateRepairObjective();}}}
let incomeAccumulator=0,systemsAccumulator=0;function gameLoop(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;let dx=joystickVector.x,dy=joystickVector.y;if(keys.has("a")||keys.has("arrowleft"))dx-=1;if(keys.has("d")||keys.has("arrowright"))dx+=1;if(keys.has("w")||keys.has("arrowup"))dy-=1;if(keys.has("s")||keys.has("arrowdown"))dy+=1;movePlayer(dx,dy,dt);updateCamera();npcs.forEach(npc=>updateNPC(npc,now,dt));findNearby();updateClock(dt);updateGhost(dt);systemsAccumulator+=dt;if(systemsAccumulator>1){systemsAccumulator=0;updateWorldSystems(1);}incomeAccumulator+=dt;if(incomeAccumulator>12){incomeAccumulator=0;const income=Math.max(1,state.machines-(state.serviceNeeded?1:0));state.money+=income;if(state.restroomCleanliness>70&&state.visitorHappiness>80)state.reputation+=.05;updateHUD();const coin=document.createElement("span");coin.className="coin-pop";coin.textContent=`+${income}🪙`;coin.style.left="330px";coin.style.top="320px";document.getElementById("world-effects").appendChild(coin);setTimeout(()=>coin.remove(),1400);}requestAnimationFrame(gameLoop);}
function applySavedRepairState(){if(!state.brokenFixed)return;const machine=document.querySelector(".machine.broken");if(machine){if(state.serviceNeeded){machine.querySelector("b").textContent="SERVICE NEEDED";}else{machine.classList.remove("broken");machine.querySelector(".breakdown-sign")?.remove();machine.querySelector("b").textContent="BENNY'S BEST";}}refreshPickups();}
player.style.left=`${playerPosition.x}px`;player.style.top=`${playerPosition.y}px`;applySavedRepairState();applyWeather();updateRepairObjective();updateHUD();updateCamera();requestAnimationFrame(gameLoop);setInterval(saveState,5000);window.addEventListener("beforeunload",saveState);
