const SAVE_KEY = "coolCatCasinoSave";
const MAX_MACHINES=15;
const defaults = {money:100,reputation:50,machines:1,introSeen:false,day:1,minutes:480,playerX:830,playerY:760,quest:0,brokenFixed:false,repairStage:"not_started",parts:{wires:0,springs:0,screws:0,circuitBoards:0},foundParts:[],lastServiced:"None yet",expansions:[],music:20,sfx:65,weather:"Drizzle",weatherDaysLeft:3,seasonDay:1,restroomCleanliness:100,teasServed:0,spins:0,jackpots:0,vinnyMet:false,ghostMet:false,achievements:[],lastDaily:0,loyaltyPoints:0,mailClaimedDay:0,emergencyDay:0,cashOuts:0,machineCondition:100,serviceNeeded:false,visitorHappiness:82,totalVisitors:0,restroomsCleaned:0,catmUses:0,cashierUses:0,blackjackPlays:0,roulettePlays:0};
let saveExists = false;
let gameStarted = false;
let resettingSave = false;
let state = loadState();
let audioContext = null;
let musicTimer = null;
let toastTimer;
const keys = new Set();
const player = document.getElementById("player");
const world = document.getElementById("world");
const viewport = document.getElementById("game-viewport");
const prompt = document.getElementById("interaction-prompt");
const WORLD = {width:1800,height:1260};
const playerPosition = {x:state.playerX,y:state.playerY};
let lastFrame = performance.now();
let nearbyTarget = null;
let vinnyVisible = false;
let tileDebugVisible = false;

function hasProgress(saved){return !!saved&&(saved.introSeen===true||saved.money!==defaults.money||saved.reputation!==defaults.reputation||saved.machines!==defaults.machines||saved.day!==defaults.day||saved.minutes!==defaults.minutes||saved.quest>0||saved.brokenFixed||saved.repairStage!=="not_started"||saved.playerX!==defaults.playerX||saved.playerY!==defaults.playerY||saved.foundParts?.length||saved.expansions?.length||Object.values(saved.parts||{}).some(Boolean));}
function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return {...defaults,parts:{...defaults.parts}};const saved=JSON.parse(raw)||{};if(!hasProgress(saved)){saveExists=false;return {...defaults,parts:{...defaults.parts}};}saveExists=true;const loaded={...defaults,...saved,parts:{...defaults.parts,...(saved.parts||{})},introSeen:true};loaded.machines=Math.min(MAX_MACHINES,Math.max(1,Number(loaded.machines)||defaults.machines));if(loaded.brokenFixed){loaded.repairStage="complete";loaded.machines=Math.min(MAX_MACHINES,Math.max(2,loaded.machines));}else if(loaded.quest>0&&loaded.repairStage==="not_started")loaded.repairStage="gathering";return loaded;}catch{saveExists=false;return {...defaults,parts:{...defaults.parts}};}}
function saveState(){if(!gameStarted||resettingSave)return;state.playerX=Math.round(playerPosition.x);state.playerY=Math.round(playerPosition.y);localStorage.setItem(SAVE_KEY,JSON.stringify(state));saveExists=true;}
function updateHUD(){document.getElementById("money").textContent=Math.floor(state.money);document.getElementById("reputation").textContent=Math.round(state.reputation);document.getElementById("machines").textContent=state.machines;renderMachineBank();Object.keys(state.parts).forEach(part=>{const el=document.getElementById(`part-${part}`);if(el)el.textContent=state.parts[part];});document.getElementById("journal-alert").style.display=state.repairStage==="complete"&&!state.serviceNeeded?"none":"grid";const clean=Math.max(0,Math.round(state.restroomCleanliness));document.getElementById("cleanliness-fill").style.width=`${clean}%`;document.getElementById("restroom-status").textContent=clean>70?"SPARKLING":clean>35?"NEEDS A SWEEP":"OH DEAR";document.getElementById("restroom-status").style.color=clean>70?"#c7f3dc":clean>35?"#ffe17c":"#ff9b9b";document.getElementById("happiness-score").textContent=Math.round(state.visitorHappiness);updateAchievements();saveState();}
function toast(text,duration=2300){const el=document.getElementById("toast");el.textContent=text;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),duration);}

function enterCasino(){gameStarted=true;lastFrame=performance.now();document.getElementById("start-menu").classList.add("done");document.getElementById("intro").classList.add("done");saveState();}
function startNewCasino(){if(saveExists&&!confirm("Start a new casino? This will overwrite the current saved casino."))return;resettingSave=true;gameStarted=false;localStorage.removeItem(SAVE_KEY);location.reload();}
function showDeleteSaveConfirm(){document.getElementById("delete-save-confirm").classList.remove("hidden");}
function hideDeleteSaveConfirm(){document.getElementById("delete-save-confirm").classList.add("hidden");}
function deleteSavedGame(){resettingSave=true;gameStarted=false;localStorage.removeItem(SAVE_KEY);location.reload();}
function beginStory(){state.introSeen=true;enterCasino();updateHUD();setTimeout(()=>speak("Benny","Astrid! Over here. Old Faithful is making that noise again."),900);}
document.getElementById("open-letter").onclick=()=>{document.getElementById("intro-card").classList.add("hidden");document.getElementById("letter").classList.remove("hidden");};
document.getElementById("begin-game").onclick=beginStory;
document.getElementById("continue-game").onclick=()=>{enterCasino();updateHUD();};
document.getElementById("start-new-casino").onclick=startNewCasino;
document.getElementById("delete-save-button").onclick=showDeleteSaveConfirm;
document.getElementById("cancel-delete-save").onclick=hideDeleteSaveConfirm;
document.getElementById("confirm-delete-save").onclick=deleteSavedGame;
if(saveExists){document.getElementById("intro").classList.add("done");document.getElementById("start-menu").classList.remove("done");}
else document.getElementById("start-menu").classList.add("done");

function ensureAudio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();if(!musicTimer)startMusic();}
function tone(freq,duration=.12,type="sine",volume=.08){if(!audioContext||!state.sfx)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=freq;o.type=type;g.gain.setValueAtTime(volume*state.sfx/100,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);}
function startMusic(){const bpm=132,beat=60/bpm,swing=.64,bass=[130.81,146.83,164.81,174.61,196,185,174.61,164.81,146.83,164.81,174.61,196,146.83,164.81,196,220],chords=[[261.63,329.63,392,493.88],[220,277.18,329.63,415.3],[293.66,349.23,440,523.25],[196,246.94,293.66,392]],noise=audioContext.createBuffer(1,audioContext.sampleRate*.06,audioContext.sampleRate);let next=0,step=0;const data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const note=(freq,t,dur,type,gain)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain*state.music/100,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+dur+.04);};const brush=(t,gain=.018)=>{const s=audioContext.createBufferSource(),g=audioContext.createGain(),f=audioContext.createBiquadFilter();s.buffer=noise;f.type="highpass";f.frequency.value=1600;g.gain.setValueAtTime(gain*state.music/100,t);g.gain.exponentialRampToValueAtTime(.0001,t+.055);s.connect(f).connect(g).connect(audioContext.destination);s.start(t);};const playStep=(t,n)=>{const eighth=n%16,quarter=n%2===0,bar=Math.floor(n/16)%chords.length;if(quarter)note(bass[(n/2)%bass.length],t,.28,"sine",.055);if([3,7,11,15].includes(eighth)){chords[bar].forEach((freq,i)=>note(freq*(i===3?2:1),t+i*.012,.22,"triangle",.012));note(chords[bar][2]*2,t+.02,.32,"sine",.01);}if(eighth%2===1)brush(t,.01);if(eighth===4||eighth===12){note(880,t,.045,"square",.006);brush(t,.022);}};musicTimer=setInterval(()=>{if(!audioContext)return;const now=audioContext.currentTime;if(!state.music){next=now+.05;return;}if(!next||next<now)next=now+.04;while(next<now+.25){playStep(next,step);next+=step%2===0?beat*swing:beat*(1-swing);step++;}},50);}
document.getElementById("sound-toggle").onclick=()=>{ensureAudio();state.music=state.music?0:20;document.getElementById("sound-toggle").textContent=state.music?"🔊":"🔇";saveState();};
document.getElementById("new-game-button").onclick=startNewCasino;
document.addEventListener("pointerdown",ensureAudio,{once:true});

const npcData=[
 {name:"Benny",emoji:"🐈‍⬛",hat:"🧢",x:1600,y:330,home:{x:1600,y:330},lines:["Uncle Whiskers always said machines are just puzzles with bad attitudes.","Hit it with a wrench first. That's science.","Nothing's exploded today. Weird."]},
 {name:"Misty",emoji:"🐱",hat:"🎀",x:300,y:670,home:{x:300,y:670},lines:["The chips aren't the only thing stacked around here.","I don't gossip. I curate information.","Did anybody else see that?","My cousin says we need karaoke."]},
 {name:"Security Pax",emoji:"🐈",hat:"🛡️",x:400,y:290,home:{x:400,y:290},staff:true,staffAccess:true,lines:["Vault hallway is secure.","Employees only past this point."]},
 {name:"Security Nix",emoji:"🐈",hat:"🛡️",x:400,y:330,home:{x:400,y:330},staff:true,staffAccess:true,lines:["Break room clear. Vault clear.","Quiet shift. That's how we like it."]},
 {name:"Marmalade",emoji:"🐈",hat:"🍊",x:580,y:630,lines:["Every machine is lucky. Some are just shy.","I can feel a jackpot in my left whisker!", "Old Faithful and I have an understanding."]},
 {name:"Bianca",emoji:"🐱",hat:"💎",x:360,y:960,lines:["The décor is... historically committed.","Oh darling, that's just Uncle Whiskers checking on us.","This place needs a pool.","When are we getting a hotel?"]},
 {name:"Poppy",emoji:"🐈",hat:"🎓",x:1320,y:970,hats:["🎓","👒","🎩","⛑️","👑","🧢"],lines:["New machine smell? No, that's burned wires.","Tea first, roulette second!","I'd love an arcade.","Do you think this hat says 'responsible gambler'?"]},
 {name:"Sir Midnight",emoji:"🐈‍⬛",hat:"🕶️",x:540,y:960,lines:["I preferred it broken. It gave the room character.","...Nice place.","Hm.","Cool."]}
];
const npcs=[];
function createNPCs(){const layer=document.getElementById("npc-layer");npcData.forEach(data=>{const el=document.createElement("div");el.className="character npc";el.dataset.name=data.name;el.innerHTML=`<div class="speech-bubble"></div><div class="shadow"></div><div class="emoji-sprite">${data.emoji}<i>${data.hat}</i></div><span class="need-icon"></span><b class="name-tag">${data.name}</b>`;el.style.left=`${data.x}px`;el.style.top=`${data.y}px`;layer.appendChild(el);const staff=data.name==="Benny"||data.name==="Misty"||data.staff===true,staffAccess=data.name==="Benny"||data.staffAccess===true;const npc={...data,el,staff,staffAccess,active:true,activity:staff?"working":"arriving",targetX:data.x,targetY:data.y,nextMove:performance.now()+1500+Math.random()*2500,lifecycleAt:performance.now()+2500+Math.random()*2500,needs:{fun:65+Math.random()*25,thirst:70,restroom:15,money:30+Math.floor(Math.random()*50),happiness:80,patience:80}};npcs.push(npc);});}
createNPCs();

const machineNames=["MEOW MIX","PAW PAYOUT","TUNA TUMBLER","FURTUNE 500","CATNIP CASH","WHISKER WIN","MOONLIGHT 7S","SARDINE SPIN","VELVET JACKPOT","PURR-A-DICE"];
const machineSpaces=[];
const GRID={x:60,y:110,t:40,cols:42,rows:27};
const TILE={floor:"floor",wall:"wall",door:"door",furniture:"furniture",machine:"machine",counter:"counter",staff:"staff-only",exit:"exit"};
const tileMap=new Map();
let playerStepCooldown=0;
const PLAYER_STEP_DELAY=.14;
const NPC_STEP_DELAY=280;
const key=(c,r)=>`${c},${r}`;
function tileRect(c,r,w=1,h=1){return {x:GRID.x+c*GRID.t,y:GRID.y+r*GRID.t,w:w*GRID.t,h:h*GRID.t};}
function tileCenter(c,r){return {x:GRID.x+c*GRID.t+GRID.t/2,y:GRID.y+r*GRID.t+GRID.t/2};}
function setTile(c,r,type){if(c>=0&&c<GRID.cols&&r>=0&&r<GRID.rows)tileMap.set(key(c,r),type);}
function fillTiles(c,r,w,h,type){for(let y=r;y<r+h;y++)for(let x=c;x<c+w;x++)setTile(x,y,type);}
function tileType(c,r){return tileMap.get(key(c,r))||TILE.wall;}
function isPublicWalkable(type){return type===TILE.floor||type===TILE.door;}
function canUseTile(type,opts={}){return isPublicWalkable(type)||(type===TILE.staff&&opts.allowStaff);}
function canRouteTile(type,opts={}){return type===TILE.floor||type===TILE.door||(type===TILE.staff&&opts.allowStaff);}
function canOccupyTile(c,r,opts={}){return canUseTile(tileType(c,r),opts);}
function outlineRoom(c,r,w,h){fillTiles(c,r,w,1,TILE.wall);fillTiles(c,r+h-1,w,1,TILE.wall);fillTiles(c,r,1,h,TILE.wall);fillTiles(c+w-1,r,1,h,TILE.wall);}
function buildGridLayout(){
 tileMap.clear();
 fillTiles(0,0,GRID.cols,1,TILE.wall);fillTiles(0,GRID.rows-1,GRID.cols,1,TILE.wall);fillTiles(0,0,1,GRID.rows,TILE.wall);fillTiles(GRID.cols-1,0,1,GRID.rows,TILE.wall);
 fillTiles(1,1,GRID.cols-2,GRID.rows-2,TILE.floor);
 [[2,1,10,8],[0,20,20,7],[34,1,7,6],[36,15,5,11]].forEach(rect=>outlineRoom(...rect));
 fillTiles(36,20,5,1,TILE.wall);
 fillTiles(3,2,8,5,TILE.staff);fillTiles(35,2,5,4,TILE.staff);
 [[0,13,1,3],[2,6,1,1],[12,15,1,2],[11,20,3,1],[36,6,3,1],[36,17,1,2],[36,22,1,2]].forEach(rect=>fillTiles(...rect,TILE.door));
 [[5,10,6,1],[4,10,1,2],[11,10,1,2],[18,22,1,1],[39,12,1,1]].forEach(rect=>fillTiles(...rect,TILE.counter));
 [[30,7,3,2],[37,7,3,2],[33,11,4,1]].forEach(rect=>fillTiles(...rect,TILE.furniture));
 [[23,24,5,1]].forEach(rect=>fillTiles(...rect,TILE.counter));
 [[37,17,1,1],[37,22,1,1],[37,16,1,1],[38,16,1,1],[37,19,1,1],[38,19,1,1],[37,21,1,1],[38,21,1,1],[37,24,1,1],[38,24,1,1],[30,23,2,1],[33,23,2,1],[31,25,2,1],[6,22,1,1],[13,22,2,1],[9,22,2,1],[2,23,4,2],[35,2,2,1],[38,4,2,1],[4,3,1,2],[6,3,2,1],[4,5,1,1],[5,5,1,1],[6,5,1,1],[7,6,1,1],[9,6,1,1],[9,3,1,1],[9,4,1,1],[10,4,1,1],[25,5,1,2],[40,20,1,1]].forEach(rect=>fillTiles(...rect,TILE.furniture));
 machineSpaces.forEach(space=>{const c=Math.floor((space.x-GRID.x)/GRID.t),r=Math.floor((space.y-GRID.y)/GRID.t);fillTiles(c,r,Math.ceil(space.w/GRID.t),Math.ceil(space.h/GRID.t),TILE.machine);});
}
function positionGridElement(selector,c,r,w,h){const el=document.querySelector(selector);if(!el)return;const rect=tileRect(c,r,w,h);Object.assign(el.style,{left:`${rect.x-60}px`,top:`${rect.y-110}px`,right:"auto",bottom:"auto",width:`${rect.w}px`,height:`${rect.h}px`});}
function positionGridObject(selector,c,r,w,h){const el=document.querySelector(selector);if(!el)return;const rect=tileRect(c,r,w,h),parent=el.parentElement,room=parent?.classList?.contains("room");const baseX=room?60+(parseFloat(parent.style.left)||0):60,baseY=room?110+(parseFloat(parent.style.top)||0):110;Object.assign(el.style,{left:`${rect.x-baseX}px`,top:`${rect.y-baseY}px`,right:"auto",bottom:"auto",width:`${rect.w}px`,height:`${rect.h}px`});}
function applyGridLayout(){
 positionGridElement(".cashier-room",2,1,10,8);positionGridElement(".slot-room",11,1,17,18);positionGridElement(".table-room",29,4,12,10);positionGridElement(".bar-room",19,20,18,7);
 positionGridElement(".restroom-room",36,15,5,11);positionGridElement(".lounge-room",0,20,20,7);positionGridElement(".maintenance-room",34,1,7,6);
 positionGridObject(".cashier-desk",5,10,6,1);positionGridObject(".catm-one",4,10,1,2);positionGridObject(".catm-two",11,10,1,2);positionGridObject(".catm-three",18,22,1,1);positionGridObject(".catm-four",39,12,1,1);
 positionGridObject(".blackjack-table",30,7,3,2);positionGridObject(".roulette-table",37,7,3,2);positionGridObject(".craps-reserve",33,11,4,1);
 positionGridObject(".bar-counter",23,24,5,1);positionGridObject(".cafe-table-a",30,23,2,1);positionGridObject(".cafe-table-b",33,23,2,1);positionGridObject(".cafe-table-c",31,25,2,1);positionGridObject(".restroom-door",37,17,1,1);positionGridObject(".restroom-door-b",37,22,1,1);
 positionGridObject(".restroom-stall-a",37,16,1,1);positionGridObject(".restroom-sink-a",38,16,1,1);positionGridObject(".restroom-stall-b",37,19,1,1);positionGridObject(".restroom-sink-b",38,19,1,1);positionGridObject(".restroom-stall-c",37,21,1,1);positionGridObject(".restroom-sink-c",38,21,1,1);positionGridObject(".restroom-stall-d",37,24,1,1);positionGridObject(".restroom-sink-d",38,24,1,1);
 positionGridObject(".attendant-stool",36,19,1,1);positionGridObject(".attendant-supplies",37,20,1,1);positionGridObject(".attendant-bucket",38,20,1,1);positionGridObject(".attendant-cabinet",39,20,1,1);
 positionGridObject(".chair-a",6,22,1,1);positionGridObject(".chair-b",13,22,2,1);positionGridObject(".coffee-table",9,22,2,1);positionGridObject(".pool-table",2,23,4,2);positionGridObject(".shelves",35,2,2,1);positionGridObject(".workbench",38,4,2,1);
 positionGridObject(".break-label",6,2,3,1);positionGridObject(".lockers-label",4,3,1,2);positionGridObject(".staff-table-label",6,3,2,1);positionGridObject(".sink-label",4,5,1,1);positionGridObject(".drink-label",5,5,1,1);positionGridObject(".vending-label",6,5,1,1);positionGridObject(".supply-label",7,6,1,1);positionGridObject(".staff-plant-label",9,6,1,1);positionGridObject(".vault-door-label",9,3,1,1);positionGridObject(".vault-label",9,2,2,1);positionGridObject(".safe-one-label",9,4,1,1);positionGridObject(".safe-two-label",10,4,1,1);
 positionGridObject(".p1",6,18,1,1);positionGridObject(".statue",25,5,1,2);positionGridObject(".p2",40,20,1,1);
 positionGridObject(".door-slots",0,13,2,1);positionGridObject(".door-games",30,4,4,1);positionGridObject(".door-blackjack",15,3,5,1);positionGridObject(".door-roulette",31,14,4,1);
 positionGridObject(".door-cashier",12,15,1,2);positionGridObject(".door-staff",2,6,1,1);positionGridObject(".door-tea",24,20,3,1);positionGridObject(".door-lounge",11,20,3,1);positionGridObject(".door-workshop",36,6,3,1);positionGridObject(".door-restroom",36,17,1,2);positionGridObject(".door-restroom-b",36,22,1,2);
}
function machineLabel(index){return machineNames[(index-2)%machineNames.length]||`MACHINE ${index+1}`;}
function machineSymbols(index){const sets=[["7","$","7"],["F","7","P"],["T","*","7"],["$","$","7"],["C","7","C"],["W","7","$"]];return sets[index%sets.length];}
function machineSpace(index){const col=index%5,isFutureRow=index>=10,row=Math.floor(index/5),c=12+col*3,r=isFutureRow?1:7+row*7,spot={c:c+(isFutureRow&&col===4?0:1),r:isFutureRow?r+3:r+4},rect=tileRect(c,r,2,3);return {x:rect.x,y:rect.y,w:80,h:120,spot,targetX:tileCenter(spot.c,spot.r).x,targetY:tileCenter(spot.c,spot.r).y};}
function machineSlots(){const slots=[];let owned=0;if(state.machines>0){slots.push({owned:true,old:true,name:"OLD FAITHFUL",symbols:["F","7","P"],action:"slots"});owned++;}
 if(state.brokenFixed){if(owned<state.machines){slots.push({owned:true,story:true,name:"LUCKY NUMBER THREE",symbols:["L","7","3"],action:"slots"});owned++;}}
 else slots.push({story:true,broken:true,name:"OUT OF ORDER",symbols:["!","?","R"],action:"repair"});
 while(owned<state.machines){const index=slots.length;slots.push({owned:true,name:machineLabel(index),symbols:machineSymbols(index),action:"slots"});owned++;}
 while(slots.length<15)slots.push({empty:true,name:"EMPTY HOOKUP",action:"buyMachine"});
 return slots.slice(0,15);
}
function renderMachineBank(){const bank=document.getElementById("slot-bank");if(!bank)return;const slots=machineSlots();machineSpaces.length=0;bank.innerHTML=slots.map((slot,index)=>{const space=machineSpace(index);machineSpaces.push({...space,slot});const roomOrigin=tileRect(11,1),localX=space.x-roomOrigin.x,localY=space.y-roomOrigin.y;if(slot.empty)return `<button class="machine locked empty" style="left:${localX}px;top:${localY}px" data-machine-index="${index}" data-action="buy-machine"><span>+</span><b>${slot.name}</b><small>${machineCost()} COINS</small></button>`;const needsService=state.serviceNeeded&&slot.owned&&!slot.story&&index===0;const cls=`machine ${slot.old?"old ":""}${slot.broken||needsService?"broken service ":""}`;const action=slot.broken?"repair":"slots";const sign=slot.broken?'<i class="breakdown-sign">&#128295;<em>OUT OF ORDER</em></i>':"";return `<button class="${cls.trim()}" style="left:${localX}px;top:${localY}px" data-machine-index="${index}" data-action="${action}" title="${slot.story?"Lucky Number Three":slot.name}">${sign}<span>${slot.symbols[0]}</span><span>${slot.symbols[1]}</span><span>${slot.symbols[2]}</span><b>${slot.name}</b></button>`;}).join("");
 bank.querySelectorAll("[data-action]").forEach(element=>element.addEventListener("click",event=>{event.stopPropagation();runAction(element.dataset.action);}));
 applyGridLayout();
 buildGridLayout();
 rebuildMachineTargets();
 renderFloorPlanArchitecture();
 renderTileDebugOverlay();
 renderInteractionSpots();
}
function spotTarget(c,r,action,label,extra={}){const point=tileCenter(c,r);return {x:point.x,y:point.y,tile:{c,r},action,label,spotTarget:true,...extra};}
function staticInteractionTargets(){return [
 spotTarget(30,10,"blackjack","Play Blackjack"),spotTarget(31,10,"blackjack","Play Blackjack"),spotTarget(32,10,"blackjack","Play Blackjack"),
 spotTarget(37,10,"roulette","Play Roulette"),spotTarget(38,10,"roulette","Play Roulette"),spotTarget(39,10,"roulette","Play Roulette"),
 spotTarget(4,12,"catm","Use CATM"),spotTarget(11,12,"catm","Use CATM"),spotTarget(17,22,"catm","Use CATM"),spotTarget(38,12,"catm","Use CATM"),
 spotTarget(5,11,"cashier","Visit Cashier"),spotTarget(6,11,"cashier","Visit Cashier"),spotTarget(7,11,"cashier","Visit Cashier"),spotTarget(8,11,"cashier","Visit Cashier"),spotTarget(9,11,"cashier","Visit Cashier"),spotTarget(10,11,"cashier","Visit Cashier"),
 spotTarget(23,25,"tea","Order Catnip Tea"),spotTarget(24,25,"tea","Order Catnip Tea"),spotTarget(25,25,"tea","Order Catnip Tea"),spotTarget(26,25,"tea","Order Catnip Tea"),spotTarget(27,25,"tea","Order Catnip Tea"),
 spotTarget(36,18,"restroom","Clean Powder Paw Room"),spotTarget(36,23,"restroom","Clean Powder Paw Room"),spotTarget(38,18,"restroom","Clean Powder Paw Room"),spotTarget(38,23,"restroom","Clean Powder Paw Room")
];}
function passiveInteractionSpots(){return [{c:33,r:12,label:"Future craps spot"},{c:34,r:12,label:"Future craps spot"},{c:35,r:12,label:"Future craps spot"},{c:37,r:2,label:"Workshop shelves",staff:true},{c:38,r:3,label:"Benny's workbench",staff:true},{c:39,r:3,label:"Benny's workbench",staff:true}];}
function machineInteractionTargets(){return machineSpaces.map((space,index)=>{const slot=space.slot,action=slot.empty?"buy-machine":slot.action,label=slot.empty?`Buy a slot machine (${machineCost()} coins)`:slot.broken?"Inspect Lucky Number Three":`Play ${slot.name}`;return spotTarget(space.spot.c,space.spot.r,action,label,{machine:true,machineIndex:index,machineName:slot.name,empty:slot.empty});});}
function rebuildMachineTargets(){if(typeof actionTargets==="undefined")return;for(let i=actionTargets.length-1;i>=0;i--)if(actionTargets[i].machine||actionTargets[i].spotTarget)actionTargets.splice(i,1);actionTargets.push(...staticInteractionTargets(),...machineInteractionTargets());}
function allInteractionSpots(){return [...staticInteractionTargets().map(target=>({...target,type:"service"})),...machineInteractionTargets().map(target=>({...target,type:"slot"})),...passiveInteractionSpots().map(spot=>({...spot,type:spot.staff?"staff":"service"}))];}
function renderInteractionSpots(){const layer=document.getElementById("interaction-spot-layer");if(!layer)return;const cells=allInteractionSpots().map(spot=>{const rect=tileRect(spot.tile?.c??spot.c,spot.tile?.r??spot.r),slot=spot.type==="slot",staff=spot.type==="staff";return `<i class="interaction-spot ${slot?"slot-stool":""} ${staff?"staff-spot":""}" title="${spot.label}" style="left:${rect.x-60}px;top:${rect.y-110}px"><span>${slot?"◒":staff?"•":"×"}</span></i>`;});layer.innerHTML=cells.join("");}
function tileAtPoint(x,y){return {c:Math.floor((x-GRID.x)/GRID.t),r:Math.floor((y-GRID.y)/GRID.t)};}
function feetTile(feet){return tileAtPoint(feet.x,feet.y);}
function actorFeet(actor){return {x:actor.x,y:actor.y};}
function playerFeet(){return {x:playerPosition.x,y:playerPosition.y};}
function sameTile(a,b){return !!a&&!!b&&a.c===b.c&&a.r===b.r;}
function renderFeetPosition(el,feet){if(el){el.style.left=`${feet.x-GRID.x}px`;el.style.top=`${feet.y-GRID.y}px`;}}
function setPlayerToTile(tile){const point=tileCenter(tile.c,tile.r);playerPosition.x=point.x;playerPosition.y=point.y;renderFeetPosition(player,point);}
function setActorToTile(actor,tile){const point=tileCenter(tile.c,tile.r);actor.tile={c:tile.c,r:tile.r};actor.x=point.x;actor.y=point.y;actor.targetX=point.x;actor.targetY=point.y;renderFeetPosition(actor.el,point);}
function nearestWalkableTile(point,opts={}){if(!tileMap.size)buildGridLayout();const origin=feetTile(point);if(canOccupyTile(origin.c,origin.r,opts))return origin;for(let radius=1;radius<Math.max(GRID.cols,GRID.rows);radius++){for(let r=origin.r-radius;r<=origin.r+radius;r++)for(let c=origin.c-radius;c<=origin.c+radius;c++){if(Math.abs(c-origin.c)!==radius&&Math.abs(r-origin.r)!==radius)continue;if(canOccupyTile(c,r,opts))return {c,r};}}return origin;}
function renderFloorPlanArchitecture(){const layer=document.getElementById("floor-plan-layer");if(!layer)return;const cells=[];tileMap.forEach((type,id)=>{const [c,r]=id.split(",").map(Number),rect=tileRect(c,r);if(type===TILE.wall)cells.push(`<i class="floor-wall" data-tile="${id}" style="left:${rect.x-60}px;top:${rect.y-110}px;width:${rect.w}px;height:${rect.h}px"></i>`);else if(canUseTile(type,{allowStaff:true}))cells.push(`<i class="floor-cell ${type===TILE.door||type===TILE.exit?"door-cell":type===TILE.staff?"staff-cell":""}" style="left:${rect.x-60}px;top:${rect.y-110}px"></i>`);});layer.innerHTML=cells.join("");}
function renderTileDebugOverlay(){const layer=document.getElementById("tile-debug-layer");if(!layer)return;const cells=[];tileMap.forEach((type,id)=>{const [c,r]=id.split(",").map(Number),rect=tileRect(c,r);cells.push(`<i class="debug-tile debug-${type}" data-type="${type}" style="left:${rect.x-60}px;top:${rect.y-110}px;width:${rect.w}px;height:${rect.h}px"><span>${type}</span></i>`);});layer.innerHTML=cells.join("");layer.classList.toggle("show",tileDebugVisible);document.getElementById("tile-debug-button")?.classList.toggle("active",tileDebugVisible);renderFeetDebugOverlay();}
function renderFeetDebugOverlay(){const layer=document.getElementById("tile-debug-layer");if(!layer)return;layer.querySelectorAll(".feet-debug").forEach(marker=>marker.remove());if(!tileDebugVisible)return;const markers=[{name:"Astrid",x:playerPosition.x,y:playerPosition.y},...npcs.map(npc=>({name:npc.name,x:npc.x,y:npc.y}))];layer.insertAdjacentHTML("beforeend",markers.map(marker=>{const tile=feetTile(marker),type=tileType(tile.c,tile.r);return `<i class="feet-debug" title="${marker.name} feet: ${tile.c},${tile.r} ${type}" style="left:${marker.x-60}px;top:${marker.y-110}px"><span>${marker.name[0]}</span></i>`;}).join(""));}
let lastMovementDebug=0;
function debugMovementReject(fromTile,toTile,reason){const now=performance.now();if(now-lastMovementDebug<250)return;lastMovementDebug=now;const currentType=tileType(fromTile.c,fromTile.r),targetType=toTile?tileType(toTile.c,toTile.r):"none";console.log(`[movement-debug] Astrid movement rejected. current=${fromTile.c},${fromTile.r} (${currentType}) target=${toTile?`${toTile.c},${toTile.r}`:"none"} (${targetType}) reason=${reason}`);}
function movePlayer(dx,dy,dt){playerStepCooldown=Math.max(0,playerStepCooldown-dt);if(!dx&&!dy){player.classList.remove("walking");return;}normalizePlayerPosition();const current=feetTile(playerFeet());if(dx&&dy){debugMovementReject(current,null,"diagonal input blocked");player.classList.remove("walking");return;}if(playerStepCooldown>0)return;const step={c:dx>0?1:dx<0?-1:0,r:dy>0?1:dy<0?-1:0},next={c:current.c+step.c,r:current.r+step.r},opts={allowStaff:true};if(!canOccupyTile(next.c,next.r,opts)){debugMovementReject(current,next,"blocked destination feet tile");player.classList.remove("walking");return;}setPlayerToTile(next);playerStepCooldown=PLAYER_STEP_DELAY;player.classList.add("walking");}
function updateCamera(){const vw=viewport.clientWidth,vh=viewport.clientHeight;const x=Math.min(0,Math.max(vw-WORLD.width,vw/2-playerPosition.x));const y=Math.min(0,Math.max(vh-WORLD.height,vh/2-playerPosition.y));world.style.transform=`translate3d(${Math.round(x)}px,${Math.round(y)}px,0)`;}
function normalizeCharacterPositions(){npcs.forEach(npc=>{const opts={allowStaff:npcCanEnterStaff(npc)};const tile=nearestWalkableTile(actorFeet(npc),opts);setActorToTile(npc,tile);if(npc.home){const homeTile=nearestWalkableTile(npc.home,opts);npc.home=tileCenter(homeTile.c,homeTile.r);}});}
function normalizePlayerPosition(){buildGridLayout();const current=feetTile(playerFeet()),opts={allowStaff:true};if(canOccupyTile(current.c,current.r,opts)){setPlayerToTile(current);return;}const tile=nearestWalkableTile(playerFeet(),opts),point=tileCenter(tile.c,tile.r);setPlayerToTile(tile);console.log(`[movement-debug] Astrid feet moved from blocked tile ${current.c},${current.r} (${tileType(current.c,current.r)}) to ${tile.c},${tile.r} (${tileType(tile.c,tile.r)})`);toast(`Movement debug: Astrid moved to ${Math.round(point.x)}, ${Math.round(point.y)}.`);saveState();}

const activitySpots={entry:tileCenter(0,14),workshopWait:tileCenter(36,6)};
const destinationPools={
 catm:[tileCenter(4,12),tileCenter(11,12),tileCenter(17,22),tileCenter(38,12)],
 cashier:[tileCenter(5,11),tileCenter(6,11),tileCenter(7,11),tileCenter(8,11),tileCenter(9,11),tileCenter(10,11)],
 slots:[tileCenter(13,11),tileCenter(16,11),tileCenter(19,11),tileCenter(22,11),tileCenter(25,11),tileCenter(13,18),tileCenter(16,18),tileCenter(19,18),tileCenter(22,18),tileCenter(25,18)],
 tables:[tileCenter(30,10),tileCenter(31,10),tileCenter(32,10),tileCenter(37,10),tileCenter(38,10),tileCenter(39,10)],
 tea:[tileCenter(23,25),tileCenter(24,25),tileCenter(25,25),tileCenter(26,25),tileCenter(27,25)],
 restroom:[tileCenter(36,18),tileCenter(36,23),tileCenter(38,18),tileCenter(38,23)],
 lounge:[tileCenter(5,21),tileCenter(8,23),tileCenter(12,21),tileCenter(15,23)],
 leaving:[tileCenter(0,14)]
};
function pickDestination(activity){const pool=destinationPools[activity]||[activitySpots.entry];return pool[Math.floor(Math.random()*pool.length)];}
function tileRoute(fromPoint,toPoint,opts={}){if(!tileMap.size)buildGridLayout();const start=nearestWalkableTile(fromPoint,opts),goal=nearestWalkableTile(toPoint,opts),startKey=key(start.c,start.r),goalKey=key(goal.c,goal.r),queue=[start],came=new Map([[startKey,null]]);for(let i=0;i<queue.length;i++){const current=queue[i],id=key(current.c,current.r);if(id===goalKey)break;for(const [dc,dr] of [[1,0],[-1,0],[0,1],[0,-1]]){const next={c:current.c+dc,r:current.r+dr},nextKey=key(next.c,next.r);if(came.has(nextKey)||!canRouteTile(tileType(next.c,next.r),opts))continue;came.set(nextKey,id);queue.push(next);}}if(!came.has(goalKey))return [];const path=[];let cursor=goalKey;while(cursor){const [c,r]=cursor.split(",").map(Number);path.push({c,r});cursor=came.get(cursor);}return path.reverse().slice(1);}
function npcCanEnterStaff(npc){return npc?.staffAccess===true||npc?.name==="Benny";}
function setNextRouteTarget(npc){if(!npc.route?.length)return false;const next=npc.route.shift(),opts={allowStaff:npcCanEnterStaff(npc)};if(!canOccupyTile(next.c,next.r,opts))return false;setActorToTile(npc,next);npc.nextStepAt=performance.now()+NPC_STEP_DELAY;return true;}
function scheduleVisitor(npc,now){const n=npc.needs,hour=Math.floor(state.minutes/60);if(npc.activity==="leaving"){npc.active=false;npc.el.classList.add("leaving");setTimeout(()=>{npc.el.style.display="none";npc.lifecycleAt=performance.now()+(hour>=22?36000:18000)+Math.random()*24000;},700);return;}let activity;if(npc.activity==="arriving")activity="catm";else if(n.restroom>72)activity="restroom";else if(n.thirst<35)activity="tea";else if(n.money<8)activity="cashier";else if(n.fun<30)activity=Math.random()<.65?"slots":"tables";else if(n.patience<25||n.money<3||hour>=23)activity="leaving";else if(hour<12)activity=Math.random()<.6?"tea":"lounge";else if(hour<17)activity=Math.random()<.65?"slots":"tables";else if(hour<22)activity=Math.random()<.5?"tables":"lounge";else activity=Math.random()<.5?"cashier":"leaving";npc.activity=activity;const finalSpot=pickDestination(activity),opts={allowStaff:false};npc.route=tileRoute(actorFeet(npc),finalSpot,opts);npc.nextStepAt=now+NPC_STEP_DELAY;npc.lifecycleAt=now+6500+Math.random()*7000;npc.el.querySelector(".need-icon").textContent=activity==="tea"?"🍵":activity==="restroom"?"🚻":activity==="catm"?"🪙":activity==="leaving"?"🏠":"";if(npc.name==="Poppy"&&Math.random()<.45)npc.el.querySelector("i").textContent=npc.hats[Math.floor(Math.random()*npc.hats.length)];}
function resolveVisitorActivity(npc){const n=npc.needs;if(npc.activity==="catm"){n.money+=25;n.patience-=4;}if(npc.activity==="slots"||npc.activity==="tables"){const win=Math.random()<.4;n.fun+=win?30:12;n.money+=win?10:-5;n.happiness+=win?8:-2;}if(npc.activity==="tea"){n.thirst=100;n.happiness+=5;state.teasServed++;state.money+=2;}if(npc.activity==="restroom"){n.restroom=0;n.happiness+=state.restroomCleanliness>40?4:-10;state.restroomCleanliness=Math.max(0,state.restroomCleanliness-4);}if(npc.activity==="cashier"){n.money+=12;n.patience-=3;}if(npc.activity==="lounge"){n.patience+=20;n.happiness+=3;}n.fun=Math.max(0,n.fun-5);n.thirst=Math.max(0,n.thirst-7);n.restroom=Math.min(100,n.restroom+9);n.patience=Math.max(0,n.patience-5);n.happiness=Math.max(0,Math.min(100,n.happiness));if(Math.random()<.18)speak(npc.name,npc.lines[Math.floor(Math.random()*npc.lines.length)]);}
function updateNPC(npc,now,dt){if(!npc.tile)setActorToTile(npc,nearestWalkableTile(actorFeet(npc),{allowStaff:npcCanEnterStaff(npc)}));if(npc.staff){const opts={allowStaff:npcCanEnterStaff(npc)},home=nearestWalkableTile(npc.home,opts);if(!npc.busy&&!sameTile(npc.tile,home)&&!npc.route?.length)npc.route=tileRoute(actorFeet(npc),tileCenter(home.c,home.r),opts);if(npc.route?.length&&now>=(npc.nextStepAt||0)){setNextRouteTarget(npc);npc.el.classList.add("walking");}else npc.el.classList.remove("walking");return;}if(!npc.active){if(now<npc.lifecycleAt)return;npc.active=true;npc.el.style.display="block";npc.el.classList.remove("leaving");npc.el.classList.add("arriving");setActorToTile(npc,nearestWalkableTile(activitySpots.entry,{allowStaff:false}));npc.activity="arriving";npc.needs={fun:55,thirst:70,restroom:10,money:25+Math.floor(Math.random()*40),happiness:78,patience:75};state.totalVisitors++;scheduleVisitor(npc,now);setTimeout(()=>npc.el.classList.remove("arriving"),1000);return;}if(npc.route?.length&&now>=(npc.nextStepAt||0)){setNextRouteTarget(npc);npc.el.classList.add("walking");return;}npc.el.classList.remove("walking");if(!npc.route?.length&&now>npc.lifecycleAt){resolveVisitorActivity(npc);scheduleVisitor(npc,now);}}

function speak(name,text,duration=4500){const npc=npcs.find(n=>n.name===name);if(!npc)return;const bubble=npc.el.querySelector(".speech-bubble");bubble.textContent=text;bubble.classList.add("show");setTimeout(()=>bubble.classList.remove("show"),duration);}
function talkToNPC(npc){tone(440,.09);if(npc.name==="Benny")return state.serviceNeeded?openRoutineService():openBennyWorkshop();if(npc.name==="Misty")return openMistyServices();const line=npc.lines[Math.floor(Math.random()*npc.lines.length)];speak(npc.name,line);}

const requiredParts={wires:1,springs:1,screws:2,circuitBoards:1};
const partInfo={wires:{icon:"〰️",name:"Wires"},springs:{icon:"➰",name:"Springs"},screws:{icon:"🔩",name:"Screws"},circuitBoards:{icon:"🟩",name:"Circuit Board"}};
const pickupDefs=[
 {id:"wire-floor",part:"wires",x:690,y:700},{id:"spring-floor",part:"springs",x:1260,y:790},{id:"screw-floor-a",part:"screws",x:670,y:1080},{id:"screw-floor-b",part:"screws",x:1650,y:800},{id:"board-floor",part:"circuitBoards",x:1100,y:760},
 {id:"parts-box-a",box:true,x:160,y:690},{id:"parts-box-b",box:true,x:1280,y:1080}
];
const actionTargets=[];
function createPickups(){const layer=document.getElementById("pickup-layer");pickupDefs.forEach(item=>{const el=document.createElement("div");el.className=`pickup ${item.box?"parts-box":""}`;el.dataset.pickup=item.id;el.style.left=`${item.x}px`;el.style.top=`${item.y}px`;el.innerHTML=item.box?`<i>📦</i><b>PARTS BOX</b>`:`<i>${partInfo[item.part].icon}</i><b>${partInfo[item.part].name.toUpperCase()}</b>`;layer.appendChild(el);item.el=el;actionTargets.push({x:item.x+20,y:item.y+20,pickup:item,label:item.box?"Search parts box":`Pick up ${partInfo[item.part].name}`});});refreshPickups();}
function refreshPickups(){pickupDefs.forEach(item=>{if(!item.el)return;const unavailable=state.repairStage==="not_started"||state.repairStage==="complete"||state.foundParts.includes(item.id);item.el.classList.toggle("collected",unavailable);});}
function collectPickup(item){if(state.repairStage==="not_started")return toast("Benny might know what these are for.");if(state.foundParts.includes(item.id))return;let part=item.part;if(item.box){const missing=Object.keys(requiredParts).filter(key=>state.parts[key]<requiredParts[key]);part=missing.length?missing[Math.floor(Math.random()*missing.length)]:Object.keys(requiredParts)[Math.floor(Math.random()*4)];}state.parts[part]++;state.foundParts.push(item.id);item.el.classList.add("collected");toast(`Found ${partInfo[part].name}!`);tone(620,.18);updateRepairObjective();updateHUD();}
createPickups();
function findNearby(){let best=null,distance=75,playerTile=feetTile(playerFeet());actionTargets.forEach(target=>{if(target.pickup&&(state.repairStage==="not_started"||state.repairStage==="complete"||state.foundParts.includes(target.pickup.id)))return;if(target.tile){if(sameTile(playerTile,target.tile)){best=target;distance=0;}return;}const d=Math.hypot(playerPosition.x-target.x,playerPosition.y-target.y);if(d<distance){best=target;distance=d;}});npcs.forEach(npc=>{const feet=actorFeet(npc),d=Math.hypot(playerPosition.x-feet.x,playerPosition.y-feet.y);if(d<distance){best={npc,label:`Talk to ${npc.name}`};distance=d;}});if(vinnyVisible){const vinny=document.getElementById("vinny"),x=parseFloat(vinny.style.left),y=parseFloat(vinny.style.top),d=Math.hypot(playerPosition.x-x,playerPosition.y-y);if(d<distance)best={action:"vinny",label:"Talk to Vinny"};}nearbyTarget=best;prompt.classList.toggle("hidden",!best);if(best)prompt.querySelector("span").textContent=best.label;}

function interactionTargetFor(action){const playerTile=feetTile(playerFeet());return actionTargets.find(target=>target.action===action&&target.tile&&sameTile(playerTile,target.tile));}
function runAction(action,target=null){if(["slots","repair","buy-machine","blackjack","roulette","tea","catm","restroom","cashier"].includes(action)){target=target||interactionTargetFor(action);if(!target)return toast("Stand on the marked interaction spot first.");}const actions={slots:()=>openSlots(target?.machineName),repair:inspectBrokenMachine,buyMachine:buyMachine,"buy-machine":buyMachine,blackjack:()=>openMiniGame("Blackjack",10,22),roulette:()=>openMiniGame("Roulette",10,30),tea:buyTea,catm:openCATM,restroom:cleanRestroom,cashier:openMistyServices,vinny:talkVinny};actions[action]?.();}
function interact(){if(!nearbyTarget)return;if(nearbyTarget.npc)return talkToNPC(nearbyTarget.npc);if(nearbyTarget.pickup)return collectPickup(nearbyTarget.pickup);runAction(nearbyTarget.action,nearbyTarget);}
function showDialog(html){const dialog=document.getElementById("dialog");document.getElementById("dialog-body").innerHTML=html;if(!dialog.open)dialog.showModal();}
document.querySelector(".dialog-close").onclick=()=>document.getElementById("dialog").close();
document.querySelectorAll("[data-action]").forEach(element=>element.addEventListener("click",event=>{event.stopPropagation();runAction(element.dataset.action);}));

function openSlots(machineName="Old Faithful"){showDialog(`<div class="dialog-scene"><p class="chapter">Lucky Paw Slots</p><h2>${machineName}</h2><div class="reels"><span id="r1">🐟</span><span id="r2">7</span><span id="r3">🐾</span></div><p id="game-result">Three matching symbols win 60 coins. Two win 15.</p><button id="spin-game">SPIN — 5 COINS</button></div>`);document.getElementById("spin-game").onclick=spinSlots;}
function spinSlots(){if(state.money<5)return document.getElementById("game-result").textContent="Not enough Catnip Coins.";ensureAudio();state.spins++;state.loyaltyPoints++;state.money-=5;const symbols=["🐟","7","🐾","🧶","🐱"],result=[];[1,2,3].forEach((n,i)=>{result.push(symbols[Math.floor(Math.random()*symbols.length)]);document.getElementById(`r${n}`).textContent=result[i];tone(250+i*80,.12,"square");});if(new Set(result).size===1){state.money+=60;state.reputation+=2;state.jackpots++;document.getElementById("game-result").textContent="JACKPOT! +60 coins!";jackpot();}else if(new Set(result).size===2){state.money+=15;document.getElementById("game-result").textContent="A tidy little win! +15 coins.";}else document.getElementById("game-result").textContent="Not this time. Old Faithful coughs politely.";updateHUD();}
function jackpot(){npcs.forEach(npc=>speak(npc.name,npc.name==="Sir Midnight"?"...Nice.":"JACKPOT!"));for(let i=0;i<24;i++){const p=document.createElement("i");p.className="particle";p.style.left=`${playerPosition.x+(Math.random()-.5)*300}px`;p.style.top=`${playerPosition.y+(Math.random()-.5)*140}px`;document.getElementById("world-effects").appendChild(p);setTimeout(()=>p.remove(),1300);}tone(880,.4,"triangle",.15);}
function hasAllParts(){return Object.keys(requiredParts).every(part=>state.parts[part]>=requiredParts[part]);}
function updateRepairObjective(){if(state.serviceNeeded)return document.getElementById("quest-text").textContent="Ask Benny to service the sparking machine";if(state.repairStage==="not_started")document.getElementById("quest-text").textContent="Talk to Benny about the broken machine";else if(state.repairStage==="gathering"){const missing=Object.keys(requiredParts).filter(part=>state.parts[part]<requiredParts[part]);document.getElementById("quest-text").textContent=missing.length?`Gather repair parts (${Object.keys(requiredParts).length-missing.length}/${Object.keys(requiredParts).length} types ready)`:"Return to Benny with the repair parts";}else if(state.repairStage==="repairing")document.getElementById("quest-text").textContent="Help Benny repair the machine";else document.getElementById("quest-text").textContent="Grow Floor 1: own 15 slots and build reputation";}
function beginRepairQuest(){state.repairStage="gathering";state.quest=1;document.getElementById("dialog").close();refreshPickups();updateRepairObjective();updateHUD();toast("Repair quest started — parts are scattered around the casino.");setTimeout(()=>speak("Poppy","New machine smell? No, that's burned wires."),900);}
function openBennyWorkshop(){if(state.repairStage==="complete")return showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Workshop</h2><p>“Nothing's exploded. Weird.”</p><div class="story-note">Last serviced: ${state.lastServiced}</div></div>`);if(state.repairStage==="not_started"){showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny</h2><p>“Uncle Whiskers always said machines are just puzzles with bad attitudes.”</p><p>Old Lucky Number Three needs wires, a spring, two screws, and a circuit board. Some parts are lying around; check the old boxes too.</p><button id="accept-repair">HELP BENNY REPAIR IT</button></div>`);document.getElementById("accept-repair").onclick=beginRepairQuest;return;}const ready=hasAllParts();showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Workshop</h2><p>“${ready?"Hit it with a wrench first. That's science.":"Nothing's exploded today. Weird."}”</p>${partsChecklist()}<p>Short on something? Benny keeps questionably organized spares.</p><div class="benny-shop">${Object.keys(requiredParts).map(part=>`<button data-buy-part="${part}">Buy ${partInfo[part].name} — ${part==="circuitBoards"?8:4}🪙</button>`).join("")}</div>${ready?'<button id="start-repair">REPAIR THE MACHINE</button>':''}</div>`);document.querySelectorAll("[data-buy-part]").forEach(button=>button.onclick=()=>buyPart(button.dataset.buyPart));if(ready)document.getElementById("start-repair").onclick=startRepairAnimation;}
function buyPart(part){const cost=part==="circuitBoards"?8:4;if(state.money<cost)return toast("Not enough Catnip Coins.");state.money-=cost;state.parts[part]++;updateRepairObjective();updateHUD();state.serviceNeeded?openRoutineService():openBennyWorkshop();}
function partsChecklist(){return `<div class="journal-parts">${Object.keys(requiredParts).map(part=>{const have=state.parts[part],need=requiredParts[part];return `<div class="journal-part ${have>=need?'have':''}">${partInfo[part].icon} ${partInfo[part].name}<br><b>${have}/${need}</b></div>`;}).join("")}</div>`;}
function getBenny(){return npcs.find(npc=>npc.name==="Benny");}
function brokenMachineSpace(){if(!machineSpaces.length)renderMachineBank();return state.repairStage==="complete"?machineSpaces.find(space=>space.slot?.owned&&!space.slot?.empty)||machineSpaces[0]:machineSpaces.find(space=>space.slot?.broken)||machineSpaces[1]||machineSpaces[0];}
function waitForBennyRoute(benny,timeout=12000){return new Promise(resolve=>{const started=performance.now(),timer=setInterval(()=>{if(!benny.route?.length||performance.now()-started>timeout){benny.route=[];clearInterval(timer);benny.el.classList.remove("walking");resolve();}},NPC_STEP_DELAY);});}
function repairSparkAt(point){for(let i=0;i<4;i++){const spark=document.createElement("i");spark.className="particle";spark.style.left=`${point.x+(Math.random()-.5)*70}px`;spark.style.top=`${point.y-45+Math.random()*55}px`;document.getElementById("world-effects").appendChild(spark);setTimeout(()=>spark.remove(),1200);}}
async function performBennyMachineVisit(onProgress=()=>{}){const benny=getBenny(),space=brokenMachineSpace();if(!benny||!space)return;const target=tileCenter(space.spot.c,space.spot.r),home=benny.home||tileCenter(38,3);benny.busy=true;benny.activity="repairing";benny.route=tileRoute(actorFeet(benny),target,{allowStaff:true});benny.nextStepAt=performance.now();benny.el.querySelector(".need-icon").textContent="🔧";speak("Benny","On my way. Try not to let it explode.",3000);onProgress(12,"Benny is walking over from the workshop...");await waitForBennyRoute(benny);benny.el.classList.add("repairing");for(let i=0;i<5;i++){onProgress(22+i*12,["Checking the cabinet panel...","Tightening the noisy bit...","Applying calibrated percussive maintenance...","Reconnecting the last wire...","Listening for suspicious rattles..."][i]);repairSparkAt(target);tone(i%2?430:180,.08,i%2?"square":"sawtooth");await new Promise(resolve=>setTimeout(resolve,520));}benny.el.classList.remove("repairing");onProgress(92,"Benny is heading back to the workshop...");benny.route=tileRoute(actorFeet(benny),home,{allowStaff:true});benny.nextStepAt=performance.now();await waitForBennyRoute(benny);benny.el.querySelector(".need-icon").textContent="";benny.busy=false;benny.activity="working";}
function inspectBrokenMachine(){if(state.repairStage==="not_started")return toast("OUT OF ORDER — Benny will know what it needs.");if(state.repairStage==="complete")return openSlots();showMaintenanceJournal();}
async function startRepairAnimation(){if(!hasAllParts())return toast("The repair kit is still missing parts.");ensureAudio();state.repairStage="repairing";updateRepairObjective();showDialog(`<div class="dialog-scene"><p class="chapter">Maintenance Team-Up</p><h2>Astrid & Benny at Work</h2><div class="repair-stage"><div class="repair-cats">🐈　🐈‍⬛</div><div class="repair-wrench">🔧</div><div class="repair-sparks">✦ ⚡ ✦</div><div class="progress-track"><div class="progress-fill" id="repair-progress"></div></div></div><p id="repair-status">Benny is leaving the workshop...</p></div>`);document.querySelector(".dialog-close").disabled=true;await performBennyMachineVisit((progress,status)=>{const fill=document.getElementById("repair-progress"),text=document.getElementById("repair-status");if(fill)fill.style.width=`${progress}%`;if(text)text.textContent=status;spawnRepairSparks();});const fill=document.getElementById("repair-progress"),text=document.getElementById("repair-status");if(fill)fill.style.width="100%";if(text)text.textContent="Benny gives the machine one last proud tap.";setTimeout(finishRepair,350);}
function spawnRepairSparks(){for(let i=0;i<3;i++){const spark=document.createElement("i");spark.className="particle";spark.style.left=`${470+Math.random()*80}px`;spark.style.top=`${390+Math.random()*60}px`;document.getElementById("world-effects").appendChild(spark);setTimeout(()=>spark.remove(),1200);}}
function finishRepair(){Object.keys(requiredParts).forEach(part=>state.parts[part]-=requiredParts[part]);state.brokenFixed=true;state.repairStage="complete";state.quest=2;state.machines=Math.min(MAX_MACHINES,state.machines+1);state.reputation+=8;state.lastServiced=`Lucky Number Three — Day ${state.day}`;const machine=document.querySelector(".machine.broken");if(machine){machine.classList.remove("broken");machine.querySelector(".breakdown-sign")?.remove();machine.querySelector("b").textContent="BENNY'S BEST";}document.querySelector(".dialog-close").disabled=false;showDialog(`<div class="dialog-scene"><div class="portrait">🎰✨</div><h2>Back in Business!</h2><p>Lucky Number Three hums to life and begins earning Catnip Coins.</p><div class="story-note">Benny: “Only two screws left over. That's basically a record.”</div></div>`);refreshPickups();updateRepairObjective();updateHUD();tone(880,.45,"triangle",.16);speak("Poppy","New machine smell? No, that's burned wires.");setTimeout(()=>speak("Sir Midnight","I preferred it broken. It gave the room character."),1800);}
function showMaintenanceJournal(){const status=state.repairStage==="complete"?"Operational":state.repairStage==="repairing"?"Repair in progress":"Out of Order";showDialog(`<div class="journal-list"><p class="chapter">Maintenance Journal</p><h2>🔧 Uncle Whiskers' Service Log</h2><div class="journal-row ${state.brokenFixed?'done':''}"><div><b>Lucky Number Three</b><small> Slot Machine • West Floor</small></div><strong>${status}</strong></div>${partsChecklist()}<div class="journal-row"><span>Repair progress</span><b>${state.repairStage==="complete"?'100%':hasAllParts()?'Parts ready':state.repairStage==="not_started"?'Not diagnosed':'Gathering parts'}</b></div><div class="story-note">Last machine serviced: ${state.lastServiced}</div></div>`);}
document.getElementById("journal-button").onclick=showMaintenanceJournal;
function openMiniGame(name,cost,prize){showDialog(`<div class="dialog-scene"><div class="portrait">${name==="Blackjack"?"🃏":"🎡"}</div><h2>${name}</h2><p id="game-result">A round costs ${cost} coins. Win ${prize}.</p><button id="play-mini">PLAY</button></div>`);document.getElementById("play-mini").onclick=()=>{if(state.money<cost)return document.getElementById("game-result").textContent="Not enough coins.";if(name==="Blackjack")state.blackjackPlays++;if(name==="Roulette")state.roulettePlays++;state.money-=cost;const win=Math.random()<.43;if(win){state.money+=prize;document.getElementById("game-result").textContent=`A classy win! +${prize} coins.`;tone(660,.2);}else document.getElementById("game-result").textContent="The house wins. It tries not to look smug.";updateHUD();};}
function buyTea(){if(state.money<3)return toast("Even tea requires three coins.");state.money-=3;state.teasServed++;state.visitorHappiness=Math.min(100,state.visitorHappiness+1);toast("Minty Meow Tea: movement feels extra smooth. 🍵");tone(520,.18);updateHUD();}
function machineCost(){return 50+Math.max(0,state.machines-1)*25;}
function buyMachine(){if(state.machines>=MAX_MACHINES)return toast("Lucky Paw Slots already has all 15 machine spaces filled.");const cost=machineCost();if(state.money<cost)return toast(`A new machine costs ${cost} Catnip Coins.`);state.money-=cost;state.machines++;state.machineCondition=Math.min(100,state.machineCondition+10);state.reputation+=1;toast(`New slot machine installed! Income increased. Next: ${machineCost()} coins.`);tone(620,.18);updateHUD();}
document.getElementById("buy-machine-button").onclick=()=>runAction("buy-machine");
document.getElementById("tile-debug-button").onclick=()=>{tileDebugVisible=!tileDebugVisible;renderTileDebugOverlay();};
function openCATM(){state.catmUses++;showDialog(`<div class="dialog-scene"><div class="portrait">🏧🐾</div><h2>CATM</h2><p>Catnip Automated Teller Machine</p><div class="service-grid"><button id="catm-withdraw">Withdraw 20 coins</button><button id="catm-emergency">Emergency coin recovery</button></div><p class="visitor-detail">Visitors use CATMs before playing so they don't wander forever with empty pockets.</p></div>`);document.getElementById("catm-withdraw").onclick=()=>{state.money+=20;state.loyaltyPoints++;toast("Withdrew 20 Catnip Coins.");updateHUD();};document.getElementById("catm-emergency").onclick=()=>{if(state.money>0)return toast("Emergency coins are only for totally empty pockets.");if(state.emergencyDay===state.day)return toast("Emergency recovery already used today.");state.money=15;state.emergencyDay=state.day;toast("CATM issued 15 emergency coins. Uncle would approve.");updateHUD();};updateHUD();}
function openMistyServices(){state.cashierUses++;showDialog(`<div class="dialog-scene"><div class="portrait">🐱🎀</div><h2>Misty's Counter</h2><p>“I don't gossip. I curate information.”</p><div class="service-grid"><button id="daily-reward">Daily reward</button><button id="loyalty-reward">Loyalty reward</button><button id="lost-found">Lost & found</button><button id="mail-button">Mail</button><button id="emergency-misty">Emergency coins</button><button id="cash-bonus">Cash out bonus</button></div></div>`);document.getElementById("daily-reward").onclick=()=>{if(state.lastDaily===state.day)return toast("Misty says you already got today's reward.");state.money+=25;state.lastDaily=state.day;toast("Daily reward: +25 coins.");updateHUD();};document.getElementById("loyalty-reward").onclick=()=>{if(state.loyaltyPoints<3)return toast("Earn 3 loyalty points from CATMs and games first.");state.loyaltyPoints-=3;state.money+=35;toast("Loyalty reward: +35 coins.");updateHUD();};document.getElementById("lost-found").onclick=()=>{if(state.lostFoundDay===state.day)return toast("Lost and found is empty today.");state.lostFoundDay=state.day;state.parts.screws++;toast("Found a screw in a velvet coin pouch.");updateHUD();};document.getElementById("mail-button").onclick=()=>{if(state.mailClaimedDay===state.day)return toast("No more mail today.");state.mailClaimedDay=state.day;state.reputation+=1;toast("Fan mail from a kitten: +1 reputation.");updateHUD();};document.getElementById("emergency-misty").onclick=()=>{if(state.money>0)return toast("Misty only opens the emergency tin when you're broke.");state.money=20;toast("Misty slides over 20 coins and pretends not to care.");updateHUD();};document.getElementById("cash-bonus").onclick=()=>{if(state.money<100)return toast("Cash out bonus starts at 100 coins.");state.money+=10;state.cashOuts++;toast("Responsible cash-out bonus: +10 coins.");updateHUD();};updateHUD();}
function cleanRestroom(){state.restroomCleanliness=100;state.restroomsCleaned++;state.reputation+=1;toast("The Powder Paw Room sparkles. Customers appreciate it.");tone(540,.2);updateHUD();}
function openRoutineService(){const ready=state.parts.wires>=1&&state.parts.screws>=1;showDialog(`<div class="dialog-scene"><div class="portrait">🐈‍⬛🧢</div><h2>Benny's Service Call</h2><p>“Hit it with a wrench first. That's science.”</p><p>Routine repair needs 1 wire and 1 screw.</p><div class="journal-parts"><div class="journal-part ${state.parts.wires>=1?'have':''}">〰️ Wires<br><b>${state.parts.wires}/1</b></div><div class="journal-part ${state.parts.screws>=1?'have':''}">🔩 Screws<br><b>${state.parts.screws}/1</b></div></div><div class="benny-shop"><button data-buy-part="wires">Buy Wires — 4🪙</button><button data-buy-part="screws">Buy Screws — 4🪙</button></div>${ready?'<button id="routine-service">SERVICE MACHINE</button>':''}</div>`);document.querySelectorAll("[data-buy-part]").forEach(button=>button.onclick=()=>buyPart(button.dataset.buyPart));if(ready)document.getElementById("routine-service").onclick=async()=>{document.getElementById("routine-service").disabled=true;document.getElementById("dialog").close();toast("Benny heads to the noisy machine.");await performBennyMachineVisit();state.parts.wires--;state.parts.screws--;state.serviceNeeded=false;state.machineCondition=100;state.lastServiced=`Routine service — Day ${state.day}`;const machine=document.querySelector(".machine.broken");if(machine){machine.classList.remove("broken","service");machine.querySelector("b").textContent=machine.title||"SERVICED";}toast("Benny services the machine. It settles down.");tone(700,.25);updateRepairObjective();updateHUD();};}

const achievementDefs=[
 ["Lucky Number Three","Repair Lucky Number Three",()=>state.brokenFixed],
 ["Own 5 Slots","Own 5 Floor 1 slot machines",()=>state.machines>=5],
 ["Own 10 Slots","Own 10 Floor 1 slot machines",()=>state.machines>=10],
 ["Own 15 Slots","Fill every Floor 1 slot machine space",()=>state.machines>=15],
 ["Powder Paw Clean-Up","Clean the Powder Paw Rooms",()=>state.restroomsCleaned>=1],
 ["Tea Service","Serve 25 catnip teas",()=>state.teasServed>=25],
 ["CATM Customer","Use a CATM",()=>state.catmUses>=1],
 ["Guest Relations","Use Misty's cashier/concierge counter",()=>state.cashierUses>=1],
 ["First Spin","Take your first slot spin",()=>state.spins>=1],
 ["First Jackpot","Hit any slot jackpot",()=>state.jackpots>=1],
 ["Blackjack Table","Play blackjack",()=>state.blackjackPlays>=1],
 ["Roulette Wheel","Play roulette",()=>state.roulettePlays>=1],
 ["Meet Vinny","Talk to Vinny",()=>state.vinnyMet],
 ["Spot Uncle Whiskers","See Uncle Whiskers after 10 PM",()=>state.ghostMet],
 ["Local Favorite","Reach 75 reputation",()=>state.reputation>=75],
 ["Floor 1 Legend","Reach 100 reputation",()=>state.reputation>=100]
];
function updateAchievements(){let changed=false;achievementDefs.forEach(([name,,test])=>{if(test()&&!state.achievements.includes(name)){state.achievements.push(name);changed=true;}});return changed;}
function showAchievements(){updateAchievements();showDialog(`<div class="dialog-scene"><p class="chapter">Separate from Blueprints</p><h2>Achievements</h2><div class="achievement-grid">${achievementDefs.map(([name,desc])=>`<div class="achievement-card ${state.achievements.includes(name)?'unlocked':''}">${state.achievements.includes(name)?'🏆':'🔒'} <b>${name}</b><br><small>${desc}</small></div>`).join("")}</div></div>`);}
document.getElementById("achievements-button").onclick=showAchievements;

const expansions=[
 {name:"Repair Lucky Number Three",goal:"Bring the story machine back online",test:()=>state.brokenFixed},
 {name:"Own 5 Floor 1 Slots",goal:"Build the first working slot row",test:()=>state.machines>=5},
 {name:"Own 10 Floor 1 Slots",goal:"Complete the original two slot rows",test:()=>state.machines>=10},
 {name:"Own 15 Floor 1 Slots",goal:"Fill all current Floor 1 slot hookups",test:()=>state.machines>=15},
 {name:"Floor 1 Reputation",goal:"Reach 100 reputation before upper-floor plans open",test:()=>state.reputation>=100},
 {name:"Later Floors Locked",goal:"Arcade, hotel, VIP, and resort plans unlock on future floors",locked:true}
];
function renderExpansions(){document.getElementById("expansion-list").innerHTML=expansions.map((item,i)=>{const complete=!item.locked&&item.test?.();return `<article class="expansion-item ${complete?'unlocked':''}"><b>${complete?'✓ ':'🔒 '}${i+1}. ${item.name}</b><small>${complete?'Floor 1 milestone complete':item.goal}</small><button disabled>${complete?'COMPLETE':'LOCKED'}</button></article>`;}).join("");}
function buildExpansion(index){toast("Uncle's later blueprints are locked until future floors open.");}
document.getElementById("expansion-button").onclick=()=>{renderExpansions();document.getElementById("expansion-panel").classList.add("open");};document.querySelector(".panel-close").onclick=()=>document.getElementById("expansion-panel").classList.remove("open");

function showVinny(){const el=document.getElementById("vinny");el.classList.remove("hidden");el.style.left="1240px";el.style.top="770px";vinnyVisible=true;setTimeout(()=>{if(vinnyVisible){el.classList.add("hidden");vinnyVisible=false;}},22000);}
function talkVinny(){state.vinnyMet=true;const lines=["These coins? Completely legitimate. Mostly.","Never trust a dealer with cleaner paws than you.","I know a guy. I am the guy."];const line=lines[Math.floor(Math.random()*lines.length)];showDialog(`<div class="dialog-scene"><div class="portrait">🦝🎩</div><h2>Vinny</h2><p>“${line}”</p><p>Give Vinny 15 coins for a mystery deal?</p><button id="vinny-deal">MAKE THE DEAL</button></div>`);document.getElementById("vinny-deal").onclick=()=>{if(state.money<15)return toast("Vinny sighs. 'Come back with the lettuce.'");state.money-=15;if(state.repairStage==="gathering"&&Math.random()<.45){const missing=Object.keys(requiredParts).filter(part=>state.parts[part]<requiredParts[part]);const part=missing.length?missing[Math.floor(Math.random()*missing.length)]:"screws";state.parts[part]++;toast(`Vinny's envelope contained ${partInfo[part].name}. Don't ask.`);updateRepairObjective();}else{const reward=Math.random()<.7?30:5;state.money+=reward;toast(`Vinny's envelope contained ${reward} coins.`);}document.getElementById("vinny-deal").disabled=true;updateHUD();};}
setTimeout(showVinny,18000+Math.random()*18000);setInterval(()=>{if(!vinnyVisible&&Math.random()<.45)showVinny();},45000);

document.addEventListener("keydown",event=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","w","a","s","d","W","A","S","D"].includes(event.key))event.preventDefault();keys.add(event.key.toLowerCase());if(event.key.toLowerCase()==="e"||event.key==="Enter")interact();});document.addEventListener("keyup",event=>keys.delete(event.key.toLowerCase()));
prompt.addEventListener("pointerdown",interact);

const weatherTypes=["Sunny","Drizzle","Rain","Thunderstorm","Snow"],weatherIcons={Sunny:"☀️",Drizzle:"🌦️",Rain:"🌧️",Thunderstorm:"⛈️",Snow:"❄️"},seasons=["Spring","Summer","Autumn","Winter"],seasonIcons={Spring:"🌸",Summer:"☀️",Autumn:"🍂",Winter:"❄️"};
function currentSeason(){return seasons[Math.floor((state.day-1)/14)%seasons.length];}
function chooseWeather(){const season=currentSeason(),pool=season==="Winter"?["Snow","Snow","Sunny","Rain"]:season==="Summer"?["Sunny","Sunny","Drizzle","Thunderstorm"]:["Sunny","Drizzle","Rain","Thunderstorm"];state.weather=pool[Math.floor(Math.random()*pool.length)];state.weatherDaysLeft=2+Math.floor(Math.random()*4);applyWeather();}
function applyWeather(){document.getElementById("weather-label").textContent=`${weatherIcons[state.weather]} ${state.weather}`;document.getElementById("season-chip").textContent=`${seasonIcons[currentSeason()]} ${currentSeason()}`;let layer=document.querySelector(".weather-particles");if(!layer){layer=document.createElement("div");layer.className="weather-particles";document.querySelector(".outside-strip").appendChild(layer);}layer.innerHTML="";if(state.weather==="Snow")for(let i=0;i<35;i++){const flake=document.createElement("i");flake.className="snowflake";flake.textContent="❄";flake.style.left=`${Math.random()*100}%`;flake.style.top=`${-Math.random()*800}px`;flake.style.animationDelay=`${Math.random()*6}s`;layer.appendChild(flake);}if(state.weather==="Thunderstorm"){const flash=document.createElement("i");flash.className="thunder-flash";layer.appendChild(flash);}}
function newGameDay(){state.weatherDaysLeft--;if(state.weatherDaysLeft<=0)chooseWeather();state.restroomCleanliness=Math.max(0,state.restroomCleanliness-2);state.seasonDay=(state.seasonDay||1)+1;updateHUD();}
function weatherComment(){if(state.weather==="Rain"||state.weather==="Drizzle")return Math.random()<.5?["Bianca","Darling, rainy days are excellent for tea."]:["Marmalade","I refuse to get my paws wet."];if(state.weather==="Snow")return ["Poppy","Snow is just confetti with boundaries."];if(state.weather==="Thunderstorm")return ["Misty","That thunder was not one of Benny's machines. Probably."];return ["Bianca","Finally, weather worthy of my sunglasses."];}
setInterval(()=>{if(!gameStarted)return;if(Math.random()<.28){const [name,line]=weatherComment();speak(name,line);}if(state.weather==="Thunderstorm"&&Math.random()<.35){const flash=document.querySelector(".thunder-flash");if(flash){flash.classList.remove("flash");void flash.offsetWidth;flash.classList.add("flash");tone(70,.5,"sawtooth",.05);}}},14000);

let ghostAccumulator=0,ghostPresent=false;
const ghostSpots=[{...tileCenter(31,10),type:"tables"},{...tileCenter(33,20),type:"cafe"},{...tileCenter(14,18),type:"slots"},{...tileCenter(12,22),type:"lounge"}];
function updateGhost(dt){const hour=Math.floor(state.minutes/60);if(hour<22&&hour>=6)return;ghostAccumulator+=dt;if(ghostAccumulator<18||ghostPresent)return;ghostAccumulator=0;if(Math.random()>.42)return;state.ghostMet=true;const ghost=document.getElementById("uncle-ghost"),spot=ghostSpots[Math.floor(Math.random()*ghostSpots.length)];ghost.style.left=`${spot.x}px`;ghost.style.top=`${spot.y}px`;ghost.classList.remove("hidden");ghostPresent=true;const messages=["You feel like Uncle Whiskers is proud of you.","Someone left fresh catnip tea on the table. Strange...","For a moment, you could swear you heard him laugh."];setTimeout(()=>toast(messages[Math.floor(Math.random()*messages.length)],5000),1200);if(Math.random()<.3){setTimeout(()=>speak("Misty","Did anybody else see that?",5000),1700);setTimeout(()=>speak("Bianca","Oh darling, that's just Uncle Whiskers checking on us.",5000),3200);}setTimeout(()=>{if(spot.type==="tables"&&Math.random()<.5){toast("The roulette ball lands on Uncle Whiskers' old number. The chair is suddenly empty.",5000);tone(720,.35,"triangle");}ghost.classList.add("hidden");ghostPresent=false;},11000);}
function updateClock(dt){const beforeDay=state.day;state.minutes+=dt/12;if(state.minutes>=1440){state.minutes-=1440;state.day++;newGameDay();}const hours=Math.floor(state.minutes/60),mins=Math.floor(state.minutes%60),displayHour=hours%12||12,period=hours<12?"AM":"PM";document.getElementById("game-time").textContent=`${displayHour}:${String(mins).padStart(2,"0")} ${period}`;document.getElementById("day-label").textContent=`DAY ${state.day}`;const night=hours>=19||hours<6;document.getElementById("day-night").style.opacity=night?".46":hours>=17?".2":"0";if(beforeDay!==state.day)saveState();}
function updateWorldSystems(dt){const visitors=npcs.filter(n=>!n.staff&&n.active);document.getElementById("visitor-count").textContent=visitors.length;const avg=visitors.length?visitors.reduce((sum,n)=>sum+n.needs.happiness,0)/visitors.length:82;state.visitorHappiness=Math.max(0,Math.min(100,(state.visitorHappiness*.98)+(avg*.02)));if(state.restroomCleanliness<35)state.visitorHappiness=Math.max(0,state.visitorHappiness-dt*.4);if(state.brokenFixed&&!state.serviceNeeded){state.machineCondition-=dt*(0.012+state.machines*.001);if(state.machineCondition<=0){state.serviceNeeded=true;state.machineCondition=0;state.reputation=Math.max(0,state.reputation-3);toast("A slot machine starts coughing sparks. Benny is already frowning.");speak("Benny","Machines are just puzzles with bad attitudes.");document.querySelector('.machine:not(.locked)')?.classList.add("broken");updateRepairObjective();}}}
let incomeAccumulator=0,systemsAccumulator=0;function gameLoop(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;if(!gameStarted){updateCamera();if(tileDebugVisible)renderFeetDebugOverlay();requestAnimationFrame(gameLoop);return;}let dx=0,dy=0;if(keys.has("a")||keys.has("arrowleft"))dx-=1;if(keys.has("d")||keys.has("arrowright"))dx+=1;if(keys.has("w")||keys.has("arrowup"))dy-=1;if(keys.has("s")||keys.has("arrowdown"))dy+=1;movePlayer(dx,dy,dt);updateCamera();npcs.forEach(npc=>updateNPC(npc,now,dt));if(tileDebugVisible)renderFeetDebugOverlay();findNearby();updateClock(dt);updateGhost(dt);systemsAccumulator+=dt;if(systemsAccumulator>1){systemsAccumulator=0;updateWorldSystems(1);}incomeAccumulator+=dt;if(incomeAccumulator>12){incomeAccumulator=0;const income=Math.max(1,state.machines-(state.serviceNeeded?1:0));state.money+=income;if(state.restroomCleanliness>70&&state.visitorHappiness>80)state.reputation+=.05;updateHUD();const coin=document.createElement("span");coin.className="coin-pop";coin.textContent=`+${income}🪙`;coin.style.left="330px";coin.style.top="320px";document.getElementById("world-effects").appendChild(coin);setTimeout(()=>coin.remove(),1400);}requestAnimationFrame(gameLoop);}
function applySavedRepairState(){if(!state.brokenFixed)return;const machine=document.querySelector(".machine.broken");if(machine){if(state.serviceNeeded){machine.querySelector("b").textContent="SERVICE NEEDED";}else{machine.classList.remove("broken");machine.querySelector(".breakdown-sign")?.remove();machine.querySelector("b").textContent="BENNY'S BEST";}}refreshPickups();}
applyWeather();updateRepairObjective();updateHUD();applySavedRepairState();normalizeCharacterPositions();normalizePlayerPosition();renderFeetPosition(player,playerPosition);updateCamera();requestAnimationFrame(gameLoop);setInterval(saveState,5000);window.addEventListener("beforeunload",saveState);
